<?php

namespace Database\Seeders;

use App\Models\Agen;
use App\Models\Parameter;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AgenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete Agen");
        DB::statement("DBCC CHECKIDENT ('Agen', RESEED, 1);");


        agen::create(['kodeagen' => 'ACHING', 'namaagen' => 'ACHING', 'keterangan' => 'ACHING', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'AKS', 'namaagen' => 'AKS', 'keterangan' => 'AKS', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'AGRI KARYA SENTOSA', 'alamat' => 'MEDAN BELAWAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'EMKLN', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/10/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'AMAN INDAH MAKMUR', 'namaagen' => 'AMAN INDAH MAKMUR', 'keterangan' => 'AMAN INDAH MAKMUR', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'AMAN INDAH MAKMUR', 'alamat' => 'JL.PULAUN MENJANGAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'DEDI TAS', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2022/4/14', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'angkutan GM', 'namaagen' => 'angkutan GM', 'keterangan' => 'angkutan GM', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'ANTARA KUSUMA', 'namaagen' => 'ANTARA KUSUMA', 'keterangan' => 'ANTARA KUSUMA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'ANUGRAH', 'namaagen' => 'ANUGRAH', 'keterangan' => 'ANUGRAH', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'ASURANSI KURNIA', 'namaagen' => 'ASURANSI KURNIA', 'keterangan' => 'ASURANSI KURNIA', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '07.02.01.58', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'ATIN', 'namaagen' => 'ATIN', 'keterangan' => 'ATIN', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.ATIN', 'alamat' => 'JL.PULAU MENJANGAN ', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => '123456', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'MERRY', 'tglapproval' => '2017/11/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'BAPAK DEDI', 'namaagen' => 'BAPAK DEDI', 'keterangan' => 'BAPAK DEDI', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'BAPAK DEDI', 'alamat' => 'JL.MENJANAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'BAPAK DEDI', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2021/9/8', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'BDP INDONESIA', 'namaagen' => 'BDP INDONESIA', 'keterangan' => 'BDP INDONESIA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'BDP INDONESIA', 'alamat' => 'JL.GUNUNG KRAKATAU NO.9 MEDAN', 'notelp' => '061-6644456', 'nohp' => '0616644456', 'contactperson' => 'BDP INDONESIA', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/10/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'BIMA', 'namaagen' => 'BIMA', 'keterangan' => 'BIMA', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'BINTANG AGUNG SUKSES', 'namaagen' => 'BINTANG AGUNG SUKSES', 'keterangan' => 'BINTANG AGUNG SUKSES', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'BINTANG AGUNG SUKSES', 'alamat' => 'JL.PULAU MENJANAGAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'BINTANG AGUNG SUKSES', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2021/12/13', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'BINTANG BELAWAN', 'namaagen' => 'BINTANG BELAWAN', 'keterangan' => 'BINTANG BELAWAN', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'BINTANG BELAWAN', 'alamat' => 'TANJUNG MORAWA', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'BINTANG BELAWAN', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/10/23', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CAB', 'namaagen' => 'CAB', 'keterangan' => 'CAB', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'CAB', 'alamat' => 'JL.BINJAI', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'CAB', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2019/2/28', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CANANG INDAH', 'namaagen' => 'CANANG INDAH', 'keterangan' => 'CANANG INDAH', 'statusaktif' => '2', 'coa' => '01.03.02.02', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'CANANG INDAH ', 'alamat' => 'JL.CEMPAKA KOMP.CEMARA ASRI MEDAN', 'notelp' => '061-6630910', 'nohp' => '061-6630910', 'contactperson' => '061-6630910', 'top' => '30', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CANANG WARUNA', 'namaagen' => 'CANANG WARUNA', 'keterangan' => 'CANANG WARUNA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'CANANG WARUNA', 'alamat' => 'JL.RAYA PELABUHAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'CANANG WARUNA', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/10/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CENTRINDO PALMAX', 'namaagen' => 'CENTRINDO PALMAX', 'keterangan' => 'CENTRINDO PALMAX', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'CENTRINDO PALMAX', 'alamat' => 'JL.PULAU MENJANGAN ', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'CENTRINDO PALMAX', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2021/3/24', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CML', 'namaagen' => 'CML', 'keterangan' => 'CML', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'CIPTA MAPAN LOGISTIK', 'alamat' => 'JL.BRAHRANG', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => '123456', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/10/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CV.AULIA ABADI', 'namaagen' => 'CV.AULIA ABADI', 'keterangan' => 'CV.AULIA ABADI', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'CV.SMM', 'namaagen' => 'CV.SMM', 'keterangan' => 'CV.SMM', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'CV.SMM', 'alamat' => 'JL.KAYU PUTIH', 'notelp' => '0618826991', 'nohp' => '081362813636', 'contactperson' => 'BPK.LIMBONG', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/11/10', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'DR.IQBAL', 'namaagen' => 'DR.IQBAL', 'keterangan' => 'DR.IQBAL', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'DR.IQBAL', 'alamat' => 'JL.KAWASAN INDUSTRI MEDAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'ACEN', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/8/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'EMKL TAS ', 'namaagen' => 'EMKL TAS ', 'keterangan' => 'EMKL TAS ', 'statusaktif' => '1', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.TAS', 'alamat' => 'JL.PULAU MENJANGAN NO 3 KIM II', 'notelp' => '0616871095', 'nohp' => '0616871095', 'contactperson' => 'TAS ', 'top' => '60', 'statusapproval' => '3', 'userapproval' => 'ASAN', 'tglapproval' => '2020/6/18', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'EMKL TAS EXPORT', 'namaagen' => 'EMKL TAS EXPORT', 'keterangan' => 'EMKL TAS EXPORT', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.TAS EXPORT', 'alamat' => 'JALAN CEMARA', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'EXPORT', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2022/4/12', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'GENTA HARAPAN', 'namaagen' => 'GENTA HARAPAN', 'keterangan' => 'GENTA HARAPAN', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'JBE', 'namaagen' => 'JBE', 'keterangan' => 'JBE', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'JUMA BERLIAN EXIM', 'alamat' => 'JL.JAMIN GINTING ,KOMPLEK CITRA GARDEN BLOK 7 NO 25 MEDAN', 'notelp' => '061-8217032', 'nohp' => '061-8217032', 'contactperson' => 'JUMA BERLIAN EXIM', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/10/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'JUMA', 'namaagen' => 'JUMA', 'keterangan' => 'JUMA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.JUMA', 'alamat' => 'JL.HELVETIA', 'notelp' => '082161567869', 'nohp' => '082161567869', 'contactperson' => 'PT.JUMA', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/11/10', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'KAB', 'namaagen' => 'KAB', 'keterangan' => 'KAB', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'kantor pusat', 'namaagen' => 'kantor pusat', 'keterangan' => 'KANTOR PUSAT', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'KANTOR PUSAT', 'alamat' => 'JL.KARTINI II  DALAM NO.15 MEDAN', 'notelp' => '061-4522875', 'nohp' => '061-4522875', 'contactperson' => '061-4522875', 'top' => '30', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'KARISMA', 'namaagen' => 'KARISMA', 'keterangan' => 'KARISMA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.KARISMA', 'alamat' => 'JL.BELAWAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'KARISMA', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2018/8/28', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'KIM', 'namaagen' => 'KIM', 'keterangan' => 'KIM', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'KP. BONAR', 'namaagen' => 'KP. BONAR', 'keterangan' => 'KP. BONAR', 'statusaktif' => '1', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'KP. BONAR', 'alamat' => 'GUDANG TAS', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => '123456', 'top' => '30', 'statusapproval' => '3', 'userapproval' => 'asan', 'tglapproval' => '2022/9/13', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'LUIS', 'namaagen' => 'LUIS', 'keterangan' => 'LUIS', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.LUIS', 'alamat' => 'JL.BERLIAN SARI NO 120 KELURAHAN KEDAI DURIAN MEDAN JOHOR', 'notelp' => '061-6999991', 'nohp' => '061-6999991', 'contactperson' => '061-6999991', 'top' => '40', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'MAS', 'namaagen' => 'MAS', 'keterangan' => 'MAS', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'MAS', 'alamat' => 'K.PUTIH', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'MAS', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/7/18', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'MOTHER CARE', 'namaagen' => 'MOTHER CARE', 'keterangan' => 'MOTHER CARE', 'statusaktif' => '1', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'MOTHER CARE', 'alamat' => 'JL.KIM', 'notelp' => '123456', 'nohp' => '123466', 'contactperson' => 'MOTHER CARE', 'top' => '60', 'statusapproval' => '3', 'userapproval' => 'ASAN', 'tglapproval' => '2018/11/28', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'MSP', 'namaagen' => 'MSP', 'keterangan' => 'MSP', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.MEGAH SINAR PERMATA', 'alamat' => 'JL.BAMBU II 15 A-B DURIAN MEDAN TIMUR', 'notelp' => '061-6619195', 'nohp' => '061-6619195', 'contactperson' => '061-6619195', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PACIFIK GLOBAL MAKMUR', 'namaagen' => 'PACIFIK GLOBAL MAKMUR', 'keterangan' => 'PACIFIK GLOBAL MAKMUR', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PACIFIK GLOBAL MAKMUR', 'alamat' => 'JL.MEDAN PGN', 'notelp' => '085100494632', 'nohp' => '085100494632', 'contactperson' => 'PGN(PACIFIK GLOBAL MAKMUR)', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2017/10/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PMS', 'namaagen' => 'PMS', 'keterangan' => 'PMS', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT. BERDIKARI SBU LOGISTIC', 'namaagen' => 'PT. BERDIKARI SBU LOGISTIC', 'keterangan' => 'PT. BERDIKARI SBU LOGISTIC', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.BERDIKARI SBU LOGISTIC', 'alamat' => 'JL.DELI NO.2 MEDAN', 'notelp' => '061-694253', 'nohp' => '061-694253', 'contactperson' => '061-694253', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT. MANDIRI AGUNG SENTOSA', 'namaagen' => 'PT. MANDIRI AGUNG SENTOSA', 'keterangan' => 'PT. MANDIRI AGUNG SENTOSA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT. WIRATAMA GROUP', 'namaagen' => 'PT. WIRATAMA GROUP', 'keterangan' => 'PT. WIRATAMA GROUP', 'statusaktif' => '1', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT. WIRATAMA GROUP', 'alamat' => 'JL. IR JUANDA MEDAN', 'notelp' => '00000', 'nohp' => '08126000275', 'contactperson' => '08126000275', 'top' => '30', 'statusapproval' => '3', 'userapproval' => 'asan', 'tglapproval' => '2023/2/17', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.AQIL', 'namaagen' => 'PT.AQIL', 'keterangan' => 'PT.AQIL', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.AQIL', 'alamat' => 'JL.PULAU MENJANGAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.AQIL', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2020/1/9', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.BANDAR AGUNG PERKASA', 'namaagen' => 'PT.BANDAR AGUNG PERKASA', 'keterangan' => 'PT.BANDAR AGUNG PERKASA', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.BCM', 'namaagen' => 'PT.BCM', 'keterangan' => 'PT.BCM', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.BCM', 'alamat' => 'JL.KIM', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'BCM', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/8/8', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.BELAWAN JAYA', 'namaagen' => 'PT.BELAWAN JAYA', 'keterangan' => 'PT.BELAWAN JAYA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.BELAWAN JAYA', 'alamat' => 'KIM', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'BELAWAN JAYA', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/8/9', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.BIGI', 'namaagen' => 'PT.BIGI', 'keterangan' => 'PT.BIGI', 'statusaktif' => '1', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.BIGI', 'alamat' => 'JL.KIM 2 ,MABAR', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => '123456', 'top' => '30', 'statusapproval' => '3', 'userapproval' => 'asan', 'tglapproval' => '2020/10/15', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.BTS', 'namaagen' => 'PT.BTS', 'keterangan' => 'PT.BTS', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.BTS', 'alamat' => 'BRAHRANG', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'BTS', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/10/23', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.CIPTA KRIDA BAHARI', 'namaagen' => 'PT.CIPTA KRIDA BAHARI', 'keterangan' => 'PT.CIPTA KRIDA BAHARI', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.CITRA ANUGERAH BAHARI', 'namaagen' => 'PT.CITRA ANUGERAH BAHARI', 'keterangan' => 'PT.CITRA ANUGERAH BAHARI', 'statusaktif' => '2', 'coa' => '01.03.02.02', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.CITRA ANUGERAH BAHARI', 'alamat' => 'JL.DELI NO.2 MEDAN', 'notelp' => '061-6492523', 'nohp' => '061-6492523', 'contactperson' => '061-6492523', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.GUNTUR PUSAKA MADYA', 'namaagen' => 'PT.GUNTUR PUSAKA MADYA', 'keterangan' => 'PT.GUNTUR PUSAKA MADYA', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.HEIMT LOGISTIC', 'namaagen' => 'PT.HEIMT LOGISTIC', 'keterangan' => 'PT.HEIMT LOGISTIC', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.HEIMT LOGISTIC', 'alamat' => 'JL.CIKAMPEK', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'FRENDY', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2019/10/30', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.JASA SUMBER', 'namaagen' => 'PT.JASA SUMBER', 'keterangan' => 'PT.JASA SUMBER', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.JASA SUMBER', 'alamat' => 'JL.BINJAI', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.JASA SUMBER', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2018/4/3', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.MKT', 'namaagen' => 'PT.MKT', 'keterangan' => 'PT.MKT', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.MKT', 'alamat' => 'JLN PATUMBAK ', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.MKT', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2018/1/8', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.PASIAT MATUA', 'namaagen' => 'PT.PASIAT MATUA', 'keterangan' => 'PT.PASIAT MATUA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.PASIAT MATUA', 'alamat' => 'JL.BELAWAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.PASIAT MATUA', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2018/2/2', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.PASIFIK TEKNOLOGI', 'namaagen' => 'PT.PASIFIK TEKNOLOGI', 'keterangan' => 'PT.PASIFIK TEKNOLOGI', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.PASIFIK TEKNOLOGI ', 'alamat' => 'JL.KAWASAN INDUSTRI MEDAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.PASIFIK', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'MERRY', 'tglapproval' => '2017/11/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PT.RISET', 'namaagen' => 'PT.RISET', 'keterangan' => 'PT.RISET', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'PT.RISET', 'alamat' => 'JL.PULAU MENJANAGN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.RISET', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2020/12/17', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'PUTRA GUNA', 'namaagen' => 'PUTRA GUNA', 'keterangan' => 'PUTRA GUNA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PUTRA GUNA', 'alamat' => 'KAYU PUTIH', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PUTRA GUNA', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/9/23', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'SAMUDERA', 'namaagen' => 'SAMUDERA', 'keterangan' => 'SAMUDERA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.SAMUDERA', 'alamat' => 'JL.RAYA PELABUHAN', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'SAMUDERA', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2018/2/26', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'SARANA BERKAT ANUGERAH', 'namaagen' => 'SARANA BERKAT ANUGERAH', 'keterangan' => 'SARAN BERKAT ANUGERAH', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'SARANA BERKAT ANUGERAH', 'alamat' => 'KIM', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'SBA', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/10/1', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'SARANA TRANS SUMATERA', 'namaagen' => 'SARANA TRANS SUMATERA', 'keterangan' => 'SARANA TRANS SUMATERA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'SARANA TRANS SUMATERA', 'alamat' => 'JL.KIM', 'notelp' => '123466', 'nohp' => '12346', 'contactperson' => 'FRENDY', 'top' => '90', 'statusapproval' => '4', 'userapproval' => 'asan', 'tglapproval' => '2019/10/17', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'SILKARGO', 'namaagen' => 'SILKARGO', 'keterangan' => 'SILKARGO', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'SILKARGO', 'alamat' => 'JL.PEMUDA NO 1', 'notelp' => '06164518307', 'nohp' => '06164518307', 'contactperson' => 'SILKARGO', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2018/2/26', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'SL', 'namaagen' => 'SL', 'keterangan' => 'SL', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'SL', 'alamat' => 'TANDEM ', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PAK JONLI', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2019/8/21', 'statustas' => '99', 'jenisemkl' => '2', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS', 'namaagen' => 'TAS', 'keterangan' => 'TAS', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'TAS', 'alamat' => 'TAS', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'TAS', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2017/6/13', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS AHAI', 'namaagen' => 'TAS AHAI', 'keterangan' => 'TAS AHAI', 'statusaktif' => '1', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'TAS AHAI', 'alamat' => 'JL.KARTINI', 'notelp' => '4522875', 'nohp' => '4522875', 'contactperson' => '4522875', 'top' => '30', 'statusapproval' => '3', 'userapproval' => 'ASAN', 'tglapproval' => '2020/4/27', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS AP', 'namaagen' => 'TAS AP', 'keterangan' => 'TAS AP', 'statusaktif' => '1', 'coa' => '01.03.01.02', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'TAS AP', 'alamat' => 'JL.PULAU MENJANGAN NO 3 KIM II MABAR', 'notelp' => '061-6871096', 'nohp' => '061-6871096', 'contactperson' => '061-6871096', 'top' => '30', 'statusapproval' => '3', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '98', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'Tas asan', 'namaagen' => 'Tas asan', 'keterangan' => 'TAS ASAN', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'TAS ASAN', 'alamat' => 'JL.PULAU MENJANGAN NO 3 KIM II', 'notelp' => '0616871095', 'nohp' => '0616871095', 'contactperson' => 'KO ASAN', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'MERRY', 'tglapproval' => '2017/11/23', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'Tas Cab pekan baru', 'namaagen' => 'Tas Cab pekan baru', 'keterangan' => 'TAS CAB PEKAN BARU', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'TAS CAB PEKAN BARU', 'alamat' => 'JL.SIMPANG BINGUNG', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'TAS CAB PEKAN BARU', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2016/11/19', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS CAB.MAKASAR', 'namaagen' => 'TAS CAB.MAKASAR', 'keterangan' => 'TAS CAB.MAKASAR', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'JL.MAKASAR', 'alamat' => 'JL.MAKASAR', 'notelp' => '123456', 'nohp' => '123456', 'contactperson' => 'PT.TAS CAB.MAKASAR', 'top' => '60', 'statusapproval' => '4', 'userapproval' => 'ASAN', 'tglapproval' => '2016/10/19', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS DAVID', 'namaagen' => 'TAS DAVID', 'keterangan' => 'TAS DAVID', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'TAS DAVID', 'alamat' => 'JL.PULAU MENJANGAN NO 3 KIM II MABAR', 'notelp' => '061-6871096', 'nohp' => '061-6871096', 'contactperson' => '061-6871096', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS EXP', 'namaagen' => 'TAS EXP', 'keterangan' => 'TAS EXP', 'statusaktif' => '1', 'coa' => '01.03.02.02', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'TAS EXP', 'alamat' => 'JL.CEMPAKA KOMP CEMARA ASRI MEDAN', 'notelp' => '061-6630910', 'nohp' => '061-6630910', 'contactperson' => '061-6630910', 'top' => '30', 'statusapproval' => '3', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/9', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS LAMA', 'namaagen' => 'TAS LAMA', 'keterangan' => 'TAS LAMA', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'TAS LAMA', 'alamat' => 'JL.PULAU MENJANGAN NO 3 KIM II MABAR', 'notelp' => '061-6871096', 'nohp' => '061-6871096', 'contactperson' => '061-6871096', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAS PINK', 'namaagen' => 'TAS PINK', 'keterangan' => 'TAS PINK', 'statusaktif' => '2', 'coa' => '01.08.01.06', 'coapendapatan' => '06.02.01.01', 'namaperusahaan' => 'TAS PINK', 'alamat' => 'JL.PULAU MENJANGAN NO 3 KIM 2', 'notelp' => '061-6871096', 'nohp' => '061-6871096', 'contactperson' => '061-6871096', 'top' => '20', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TAX AP', 'namaagen' => 'TAX AP', 'keterangan' => 'TAX AP', 'statusaktif' => '2', 'coa' => '', 'coapendapatan' => '', 'namaperusahaan' => 'TAX AP', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'TETAP JAYA', 'namaagen' => 'TETAP JAYA', 'keterangan' => 'TETAP JAYA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '', 'namaperusahaan' => '', 'alamat' => '', 'notelp' => '', 'nohp' => '', 'contactperson' => '', 'top' => '0', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
        agen::create(['kodeagen' => 'WARUNA', 'namaagen' => 'WARUNA', 'keterangan' => 'WARUNA', 'statusaktif' => '2', 'coa' => '01.03.02.01', 'coapendapatan' => '06.01.01.02', 'namaperusahaan' => 'PT.WARUNA NUSA SENTANA', 'alamat' => 'JL.GAJAH MADA NO 10 MEDAN', 'notelp' => '061-4535314', 'nohp' => '061-4535314', 'contactperson' => '061-4535314', 'top' => '30', 'statusapproval' => '4', 'userapproval' => 'DHENI', 'tglapproval' => '2015/11/5', 'statustas' => '99', 'jenisemkl' => '1', 'modifiedby' => 'RYAN',]);
    }
}
