<?php

namespace Database\Seeders;

use App\Models\GajiSupirDeposito;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GajiSupirDepositoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete gajisupirdeposito");
        DB::statement("DBCC CHECKIDENT ('gajisupirdeposito', RESEED, 1);");

        gajisupirdeposito::create(['gajisupir_id' => '2', 'gajisupir_nobukti' => 'RIC 0002/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0001/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '5', 'gajisupir_nobukti' => 'RIC 0005/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0002/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '6', 'gajisupir_nobukti' => 'RIC 0006/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0003/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '9', 'gajisupir_nobukti' => 'RIC 0009/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0004/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '10', 'gajisupir_nobukti' => 'RIC 0010/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0005/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '11', 'gajisupir_nobukti' => 'RIC 0011/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0006/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '13', 'gajisupir_nobukti' => 'RIC 0013/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0007/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '14', 'gajisupir_nobukti' => 'RIC 0014/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0008/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '15', 'gajisupir_nobukti' => 'RIC 0015/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0009/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '5000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '16', 'gajisupir_nobukti' => 'RIC 0016/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0010/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '50000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '17', 'gajisupir_nobukti' => 'RIC 0017/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0011/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '75000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '18', 'gajisupir_nobukti' => 'RIC 0018/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0012/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '5000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '19', 'gajisupir_nobukti' => 'RIC 0019/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0013/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '20', 'gajisupir_nobukti' => 'RIC 0020/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0014/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '21', 'gajisupir_nobukti' => 'RIC 0021/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0015/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '22', 'gajisupir_nobukti' => 'RIC 0022/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0016/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '23', 'gajisupir_nobukti' => 'RIC 0023/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0017/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '24', 'gajisupir_nobukti' => 'RIC 0024/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0018/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '25', 'gajisupir_nobukti' => 'RIC 0025/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0019/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '26', 'gajisupir_nobukti' => 'RIC 0026/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0020/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '27', 'gajisupir_nobukti' => 'RIC 0027/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0021/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '28', 'gajisupir_nobukti' => 'RIC 0028/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0022/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '30', 'gajisupir_nobukti' => 'RIC 0030/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0023/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '31', 'gajisupir_nobukti' => 'RIC 0031/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0024/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '10', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '32', 'gajisupir_nobukti' => 'RIC 0032/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0025/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '267', 'nominal' => '50000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '33', 'gajisupir_nobukti' => 'RIC 0033/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0026/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '34', 'gajisupir_nobukti' => 'RIC 0034/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0027/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '35', 'gajisupir_nobukti' => 'RIC 0035/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0028/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '36', 'gajisupir_nobukti' => 'RIC 0036/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0029/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '37', 'gajisupir_nobukti' => 'RIC 0037/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0030/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '39', 'gajisupir_nobukti' => 'RIC 0039/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0031/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '50000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '41', 'gajisupir_nobukti' => 'RIC 0041/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0032/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '42', 'gajisupir_nobukti' => 'RIC 0042/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0033/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '44', 'gajisupir_nobukti' => 'RIC 0044/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0034/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '45', 'gajisupir_nobukti' => 'RIC 0045/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0035/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '46', 'gajisupir_nobukti' => 'RIC 0046/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0036/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '30000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '47', 'gajisupir_nobukti' => 'RIC 0047/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0037/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '30000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '49', 'gajisupir_nobukti' => 'RIC 0049/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0038/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '50', 'gajisupir_nobukti' => 'RIC 0050/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0039/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '51', 'gajisupir_nobukti' => 'RIC 0051/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0040/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '15000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '53', 'gajisupir_nobukti' => 'RIC 0053/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0041/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '30000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '54', 'gajisupir_nobukti' => 'RIC 0054/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0042/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '55', 'gajisupir_nobukti' => 'RIC 0055/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0043/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '56', 'gajisupir_nobukti' => 'RIC 0056/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0044/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '57', 'gajisupir_nobukti' => 'RIC 0057/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0045/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '58', 'gajisupir_nobukti' => 'RIC 0058/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0046/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '60', 'gajisupir_nobukti' => 'RIC 0060/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0047/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '61', 'gajisupir_nobukti' => 'RIC 0061/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0048/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '267', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '62', 'gajisupir_nobukti' => 'RIC 0062/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0049/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '63', 'gajisupir_nobukti' => 'RIC 0063/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0050/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '65', 'gajisupir_nobukti' => 'RIC 0065/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0051/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '66', 'gajisupir_nobukti' => 'RIC 0066/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0052/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '67', 'gajisupir_nobukti' => 'RIC 0067/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0053/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '68', 'gajisupir_nobukti' => 'RIC 0068/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0054/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '69', 'gajisupir_nobukti' => 'RIC 0069/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0055/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '70', 'gajisupir_nobukti' => 'RIC 0070/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0056/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '267', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '71', 'gajisupir_nobukti' => 'RIC 0071/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0057/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '72', 'gajisupir_nobukti' => 'RIC 0072/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0058/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '73', 'gajisupir_nobukti' => 'RIC 0073/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0059/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '74', 'gajisupir_nobukti' => 'RIC 0074/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0060/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '76', 'gajisupir_nobukti' => 'RIC 0076/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0061/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '30000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '78', 'gajisupir_nobukti' => 'RIC 0078/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0062/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '79', 'gajisupir_nobukti' => 'RIC 0079/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0063/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '50000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '80', 'gajisupir_nobukti' => 'RIC 0080/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0064/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '81', 'gajisupir_nobukti' => 'RIC 0081/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0065/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '82', 'gajisupir_nobukti' => 'RIC 0082/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0066/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '84', 'gajisupir_nobukti' => 'RIC 0084/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0067/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '85', 'gajisupir_nobukti' => 'RIC 0085/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0068/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '86', 'gajisupir_nobukti' => 'RIC 0086/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0069/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '87', 'gajisupir_nobukti' => 'RIC 0087/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0070/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '267', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '88', 'gajisupir_nobukti' => 'RIC 0088/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0071/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '89', 'gajisupir_nobukti' => 'RIC 0089/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0072/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '184', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '90', 'gajisupir_nobukti' => 'RIC 0090/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0073/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '91', 'gajisupir_nobukti' => 'RIC 0091/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0074/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '92', 'gajisupir_nobukti' => 'RIC 0092/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0075/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '93', 'gajisupir_nobukti' => 'RIC 0093/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0076/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '94', 'gajisupir_nobukti' => 'RIC 0094/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0077/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '97', 'gajisupir_nobukti' => 'RIC 0097/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0078/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '98', 'gajisupir_nobukti' => 'RIC 0098/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0079/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '99', 'gajisupir_nobukti' => 'RIC 0099/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0080/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '100', 'gajisupir_nobukti' => 'RIC 0100/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0081/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '101', 'gajisupir_nobukti' => 'RIC 0101/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0082/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '267', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '102', 'gajisupir_nobukti' => 'RIC 0102/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0083/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '103', 'gajisupir_nobukti' => 'RIC 0103/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0084/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '104', 'gajisupir_nobukti' => 'RIC 0104/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0085/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '106', 'gajisupir_nobukti' => 'RIC 0106/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0086/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '107', 'gajisupir_nobukti' => 'RIC 0107/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0087/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '108', 'gajisupir_nobukti' => 'RIC 0108/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0088/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '109', 'gajisupir_nobukti' => 'RIC 0109/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0089/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '111', 'gajisupir_nobukti' => 'RIC 0111/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0090/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '60000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '114', 'gajisupir_nobukti' => 'RIC 0114/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0091/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '115', 'gajisupir_nobukti' => 'RIC 0115/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0092/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '116', 'gajisupir_nobukti' => 'RIC 0116/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0093/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '117', 'gajisupir_nobukti' => 'RIC 0117/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0094/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '118', 'gajisupir_nobukti' => 'RIC 0118/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0095/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '119', 'gajisupir_nobukti' => 'RIC 0119/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0096/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '120', 'gajisupir_nobukti' => 'RIC 0120/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0097/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '121', 'gajisupir_nobukti' => 'RIC 0121/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0098/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '122', 'gajisupir_nobukti' => 'RIC 0122/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0099/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '30000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '123', 'gajisupir_nobukti' => 'RIC 0123/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0100/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '124', 'gajisupir_nobukti' => 'RIC 0124/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0101/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '46', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '125', 'gajisupir_nobukti' => 'RIC 0125/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0102/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '126', 'gajisupir_nobukti' => 'RIC 0126/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0103/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '127', 'gajisupir_nobukti' => 'RIC 0127/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0104/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '184', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '129', 'gajisupir_nobukti' => 'RIC 0129/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0105/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '130', 'gajisupir_nobukti' => 'RIC 0130/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0106/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '131', 'gajisupir_nobukti' => 'RIC 0131/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0107/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '132', 'gajisupir_nobukti' => 'RIC 0132/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0108/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '15000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '133', 'gajisupir_nobukti' => 'RIC 0133/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0109/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '134', 'gajisupir_nobukti' => 'RIC 0134/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0110/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '135', 'gajisupir_nobukti' => 'RIC 0135/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0111/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '136', 'gajisupir_nobukti' => 'RIC 0136/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0112/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '138', 'gajisupir_nobukti' => 'RIC 0138/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0113/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '140', 'gajisupir_nobukti' => 'RIC 0140/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0114/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '142', 'gajisupir_nobukti' => 'RIC 0142/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0115/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '311', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '144', 'gajisupir_nobukti' => 'RIC 0144/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0116/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '184', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '145', 'gajisupir_nobukti' => 'RIC 0145/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0117/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '30000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '146', 'gajisupir_nobukti' => 'RIC 0146/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0118/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '147', 'gajisupir_nobukti' => 'RIC 0147/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0119/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '148', 'gajisupir_nobukti' => 'RIC 0148/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0120/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '15000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '149', 'gajisupir_nobukti' => 'RIC 0149/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0121/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '15000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '150', 'gajisupir_nobukti' => 'RIC 0150/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0122/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '15000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '154', 'gajisupir_nobukti' => 'RIC 0154/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0123/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '15000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '156', 'gajisupir_nobukti' => 'RIC 0156/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0124/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '15000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '157', 'gajisupir_nobukti' => 'RIC 0157/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0125/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '15000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '159', 'gajisupir_nobukti' => 'RIC 0159/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0126/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '30000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '161', 'gajisupir_nobukti' => 'RIC 0161/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0127/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '162', 'gajisupir_nobukti' => 'RIC 0162/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0128/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '72', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '163', 'gajisupir_nobukti' => 'RIC 0163/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0129/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '164', 'gajisupir_nobukti' => 'RIC 0164/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0130/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '94', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '165', 'gajisupir_nobukti' => 'RIC 0165/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0131/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '166', 'gajisupir_nobukti' => 'RIC 0166/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0132/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '167', 'gajisupir_nobukti' => 'RIC 0167/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0133/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '168', 'gajisupir_nobukti' => 'RIC 0168/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0134/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '184', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '169', 'gajisupir_nobukti' => 'RIC 0169/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0135/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '170', 'gajisupir_nobukti' => 'RIC 0170/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0136/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '171', 'gajisupir_nobukti' => 'RIC 0171/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0137/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '172', 'gajisupir_nobukti' => 'RIC 0172/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0138/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '173', 'gajisupir_nobukti' => 'RIC 0173/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0139/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '172', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '175', 'gajisupir_nobukti' => 'RIC 0175/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0140/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '267', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '178', 'gajisupir_nobukti' => 'RIC 0178/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0141/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '76', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '179', 'gajisupir_nobukti' => 'RIC 0179/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0142/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '7', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '181', 'gajisupir_nobukti' => 'RIC 0181/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0143/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '171', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '182', 'gajisupir_nobukti' => 'RIC 0182/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0144/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '175', 'nominal' => '25000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '183', 'gajisupir_nobukti' => 'RIC 0183/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0145/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '298', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '184', 'gajisupir_nobukti' => 'RIC 0184/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0146/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '307', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '185', 'gajisupir_nobukti' => 'RIC 0185/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0147/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '305', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '187', 'gajisupir_nobukti' => 'RIC 0187/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0148/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '73', 'nominal' => '25000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '188', 'gajisupir_nobukti' => 'RIC 0188/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0149/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '146', 'nominal' => '30000', 'modifiedby' => 'ADMIN',]);
        gajisupirdeposito::create(['gajisupir_id' => '189', 'gajisupir_nobukti' => 'RIC 0189/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0150/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '60', 'nominal' => '30000', 'modifiedby' => 'CHAIRUNNISA',]);
        gajisupirdeposito::create(['gajisupir_id' => '190', 'gajisupir_nobukti' => 'RIC 0190/II/2023', 'penerimaantrucking_nobukti' => 'DPO 0151/II/2023', 'pengeluarantrucking_nobukti' => '', 'supir_id' => '22', 'nominal' => '50000', 'modifiedby' => 'CHAIRUNNISA',]);
    }
}
