<?php

namespace Database\Seeders;

use App\Models\GajiSupirDetail;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GajiSupirDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete GajiSupirDetail");
        DB::statement("DBCC CHECKIDENT ('GajiSupirDetail', RESEED, 1);");

        gajisupirdetail::create(['gajisupir_id' => '1', 'nobukti' => 'RIC 0001/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0570/I/2023', 'ritasi_nobukti' => 'RTT 0176/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '113556', 'gajikenek' => '0', 'gajiritasi' => '20400', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '1', 'nobukti' => 'RIC 0001/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0571/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '1', 'nobukti' => 'RIC 0001/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0591/I/2023', 'ritasi_nobukti' => 'RTT 0198/I/2023', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '92933', 'gajikenek' => '0', 'gajiritasi' => '40800', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '2', 'nobukti' => 'RIC 0002/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0560/I/2023', 'ritasi_nobukti' => 'RTT 0173/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '30900', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '2', 'nobukti' => 'RIC 0002/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0585/I/2023', 'ritasi_nobukti' => 'RTT 0187/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '188692', 'gajikenek' => '0', 'gajiritasi' => '20400', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '2', 'nobukti' => 'RIC 0002/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0586/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '291315', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '3', 'nobukti' => 'RIC 0003/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0551/I/2023', 'ritasi_nobukti' => 'RTT 0207/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '73680', 'gajikenek' => '0', 'gajiritasi' => '47800', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '3', 'nobukti' => 'RIC 0003/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0575/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '3', 'nobukti' => 'RIC 0003/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0576/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '75000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '3', 'nobukti' => 'RIC 0003/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0602/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '72768', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '4', 'nobukti' => 'RIC 0004/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0543/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '75000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '5', 'nobukti' => 'RIC 0005/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0574/I/2023', 'ritasi_nobukti' => 'RTT 0178/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '198180', 'gajikenek' => '0', 'gajiritasi' => '30900', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '5', 'nobukti' => 'RIC 0005/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0574/I/2023', 'ritasi_nobukti' => 'RTT 0199/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '0', 'gajikenek' => '0', 'gajiritasi' => '13600', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '5', 'nobukti' => 'RIC 0005/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0584/I/2023', 'ritasi_nobukti' => 'RTT 0200/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '359220', 'gajikenek' => '0', 'gajiritasi' => '57100', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '5', 'nobukti' => 'RIC 0005/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0598/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '129216', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '6', 'nobukti' => 'RIC 0006/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0549/I/2023', 'ritasi_nobukti' => 'RTT 0170/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '170333', 'gajikenek' => '0', 'gajiritasi' => '20400', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '6', 'nobukti' => 'RIC 0006/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0550/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '185520', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '6', 'nobukti' => 'RIC 0006/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0597/I/2023', 'ritasi_nobukti' => 'RTT 0201/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '57100', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '6', 'nobukti' => 'RIC 0006/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0599/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '123680', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '7', 'nobukti' => 'RIC 0007/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0481/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '73680', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '7', 'nobukti' => 'RIC 0007/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0561/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '7', 'nobukti' => 'RIC 0007/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0562/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '185520', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '7', 'nobukti' => 'RIC 0007/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0595/I/2023', 'ritasi_nobukti' => 'RTT 0190/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '218020', 'gajikenek' => '0', 'gajiritasi' => '47800', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '8', 'nobukti' => 'RIC 0008/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0568/I/2023', 'ritasi_nobukti' => 'RTT 0175/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '123680', 'gajikenek' => '0', 'gajiritasi' => '30600', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '8', 'nobukti' => 'RIC 0008/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0569/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '142933', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '8', 'nobukti' => 'RIC 0008/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0592/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '8', 'nobukti' => 'RIC 0008/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0593/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '9', 'nobukti' => 'RIC 0009/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0527/I/2023', 'ritasi_nobukti' => 'RTT 0203/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '327030', 'gajikenek' => '0', 'gajiritasi' => '47800', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '9', 'nobukti' => 'RIC 0009/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0572/I/2023', 'ritasi_nobukti' => 'RTT 0177/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '194210', 'gajikenek' => '0', 'gajiritasi' => '57100', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '9', 'nobukti' => 'RIC 0009/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0573/I/2023', 'ritasi_nobukti' => 'RTT 0204/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '179280', 'gajikenek' => '0', 'gajiritasi' => '44400', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '9', 'nobukti' => 'RIC 0009/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0589/I/2023', 'ritasi_nobukti' => 'RTT 0189/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '218020', 'gajikenek' => '0', 'gajiritasi' => '47800', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '9', 'nobukti' => 'RIC 0009/II/2023', 'nominaldeposito' => '0', 'nourut' => '5', 'suratpengantar_nobukti' => 'TRP 0590/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '193824', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '10', 'nobukti' => 'RIC 0010/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0552/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '10', 'nobukti' => 'RIC 0010/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0553/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '10', 'nobukti' => 'RIC 0010/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0554/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '10', 'nobukti' => 'RIC 0010/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0583/I/2023', 'ritasi_nobukti' => 'RTT 0186/I/2023', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '30900', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '11', 'nobukti' => 'RIC 0011/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0566/I/2023', 'ritasi_nobukti' => 'RTT 0205/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '142933', 'gajikenek' => '0', 'gajiritasi' => '57100', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '11', 'nobukti' => 'RIC 0011/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0567/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '147768', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '11', 'nobukti' => 'RIC 0011/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0587/I/2023', 'ritasi_nobukti' => 'RTT 0188/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '268920', 'gajikenek' => '0', 'gajiritasi' => '44400', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '11', 'nobukti' => 'RIC 0011/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0588/I/2023', 'ritasi_nobukti' => 'RTT 0206/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '291315', 'gajikenek' => '0', 'gajiritasi' => '57100', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '12', 'nobukti' => 'RIC 0012/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0523/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '92933', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '12', 'nobukti' => 'RIC 0012/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0558/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '12', 'nobukti' => 'RIC 0012/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0559/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '12', 'nobukti' => 'RIC 0012/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0580/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '142933', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '12', 'nobukti' => 'RIC 0012/II/2023', 'nominaldeposito' => '0', 'nourut' => '5', 'suratpengantar_nobukti' => 'TRP 0581/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '13', 'nobukti' => 'RIC 0013/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0556/I/2023', 'ritasi_nobukti' => 'RTT 0171/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '690000', 'gajikenek' => '0', 'gajiritasi' => '30900', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '13', 'nobukti' => 'RIC 0013/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0579/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '410000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '14', 'nobukti' => 'RIC 0014/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0557/I/2023', 'ritasi_nobukti' => 'RTT 0172/I/2023', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '343215', 'gajikenek' => '0', 'gajiritasi' => '30900', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '14', 'nobukti' => 'RIC 0014/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0582/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '178810', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '15', 'nobukti' => 'RIC 0015/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0594/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '73680', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '15', 'nobukti' => 'RIC 0015/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0596/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '85000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0555/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '92933', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0577/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0578/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '75000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0606/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '186295', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '5', 'suratpengantar_nobukti' => 'TRP 0607/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '6', 'suratpengantar_nobukti' => 'TRP 0643/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '142933', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '7', 'suratpengantar_nobukti' => 'TRP 0644/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '123680', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '16', 'nobukti' => 'RIC 0016/II/2023', 'nominaldeposito' => '0', 'nourut' => '8', 'suratpengantar_nobukti' => 'TRP 0674/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '204443', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0491/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '123680', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '2', 'suratpengantar_nobukti' => 'TRP 0492/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '214399', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '3', 'suratpengantar_nobukti' => 'TRP 0546/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '92933', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '4', 'suratpengantar_nobukti' => 'TRP 0563/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '50000', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '5', 'suratpengantar_nobukti' => 'TRP 0564/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '10000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '98512', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '6', 'suratpengantar_nobukti' => 'TRP 0565/I/2023', 'ritasi_nobukti' => 'RTT 0174/I/2023', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '193824', 'gajikenek' => '0', 'gajiritasi' => '20400', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '7', 'suratpengantar_nobukti' => 'TRP 0620/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '8', 'suratpengantar_nobukti' => 'TRP 0621/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '9', 'suratpengantar_nobukti' => 'TRP 0622/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '10', 'suratpengantar_nobukti' => 'TRP 0640/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '11', 'suratpengantar_nobukti' => 'TRP 0641/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '17', 'nobukti' => 'RIC 0017/II/2023', 'nominaldeposito' => '0', 'nourut' => '12', 'suratpengantar_nobukti' => 'TRP 0642/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '0', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '252840', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
        gajisupirdetail::create(['gajisupir_id' => '18', 'nobukti' => 'RIC 0018/II/2023', 'nominaldeposito' => '0', 'nourut' => '1', 'suratpengantar_nobukti' => 'TRP 0670/I/2023', 'ritasi_nobukti' => '-', 'komisisupir' => '5000', 'tolsupir' => '0', 'voucher' => '0', 'novoucher' => '0', 'gajisupir' => '95333', 'gajikenek' => '0', 'gajiritasi' => '0', 'biayatambahan' => '0', 'keteranganbiayatambahan' => '-', 'nominalpengembalianpinjaman' => '0', 'modifiedby' => 'ADMIN',]);
    }
}
