<?php

namespace Database\Seeders;

use App\Models\Kota;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("delete Kota");
        DB::statement("DBCC CHECKIDENT ('Kota', RESEED, 1);");

        kota::create(['kodekota' => 'BELAWAN', 'keterangan' => 'BELAWAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAYAN', 'keterangan' => 'BRAYAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CANANG', 'keterangan' => 'CANANG', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CEMARA - SIMPANG PANCING', 'keterangan' => 'CEMARA - SIMPANG PANCING', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM', 'keterangan' => 'KIM', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM II', 'keterangan' => 'KIM II', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM III', 'keterangan' => 'KIM III', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KOTA BANGUN', 'keterangan' => 'KOTA BANGUN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU', 'keterangan' => 'KRAKATAU', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR', 'keterangan' => 'MABAR', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MARELAN', 'keterangan' => 'MARELAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HELVETIA', 'keterangan' => 'HELVETIA', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HELVETIA - SIMPANG PONDOK KELAPA', 'keterangan' => 'HELVETIA - SIMPANG PONDOK KELAPA', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. PUTIH', 'keterangan' => 'K. PUTIH', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH', 'keterangan' => 'KAYU PUTIH', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PADANG BULAN', 'keterangan' => 'PADANG BULAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCING - SIMPANG AKSARA', 'keterangan' => 'PANCING - SIMPANG AKSARA', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MARTUBUNG', 'keterangan' => 'MARTUBUNG', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PAYA PASIR', 'keterangan' => 'PAYA PASIR', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERTEMPURAN', 'keterangan' => 'PERTEMPURAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SMART', 'keterangan' => 'SMART', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SIDEMPUAN', 'keterangan' => 'SIDEMPUAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SIMPANG KANTOR', 'keterangan' => 'SIMPANG KANTOR', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA', 'keterangan' => 'TANJUNG MULIA', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TITI PAPAN', 'keterangan' => 'TITI PAPAN', 'zona_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'GATOT SUBROTO - KP. LALANG TUGU PERBATASAN', 'keterangan' => 'GATOT SUBROTO - KP. LALANG TUGU PERBATASAN', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG', 'keterangan' => 'TEMBUNG', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SISINGAMANGARAJA', 'keterangan' => 'SISINGAMANGARAJA', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL', 'keterangan' => 'SUNGGAL', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI', 'keterangan' => 'SAMPALI', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MEDAN KOTA', 'keterangan' => 'MEDAN KOTA', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PASAR MERAH', 'keterangan' => 'PASAR MERAH', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KELAMBIR JAYA', 'keterangan' => 'KELAMBIR JAYA', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MARENDAL', 'keterangan' => 'MARENDAL', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS', 'keterangan' => 'AMPLAS', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (S/D POLDASU)', 'keterangan' => 'AMPLAS (S/D POLDASU)', 'zona_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI', 'keterangan' => 'BINJAI', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI - PERBATASAN TUGU BINJAI', 'keterangan' => 'BINJAI - PERBATASAN TUGU BINJAI', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'DELI TUA', 'keterangan' => 'DELI TUA', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL.KARTINI', 'keterangan' => 'JL.KARTINI', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PATUMBAK', 'keterangan' => 'PATUMBAK', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE', 'keterangan' => 'NAMORAMBE', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TALON KENAS', 'keterangan' => 'TALON KENAS', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA', 'keterangan' => 'TAMORA', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA - SIMPANG PAKAM', 'keterangan' => 'TAMORA - SIMPANG PAKAM', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANDEM', 'keterangan' => 'TANDEM', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA', 'keterangan' => 'TANJUNG MORAWA', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TITI KUNING', 'keterangan' => 'TITI KUNING', 'zona_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'ACEH SUBULUSSALAM', 'keterangan' => 'ACEH SUBULUSSALAM', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'ACEH UTARA', 'keterangan' => 'ACEH UTARA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AEK KANOPAN', 'keterangan' => 'AEK KANOPAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BALIGE', 'keterangan' => 'BALIGE', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH', 'keterangan' => 'BANDA ACEH', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANGUN PURBA', 'keterangan' => 'BANGUN PURBA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAHRANG', 'keterangan' => 'BRAHRANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRASTAGI', 'keterangan' => 'BRASTAGI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CEMARA', 'keterangan' => 'CEMARA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CIKAMPAK', 'keterangan' => 'CIKAMPAK', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'DUMAI', 'keterangan' => 'DUMAI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'DURI', 'keterangan' => 'DURI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'GALANG', 'keterangan' => 'GALANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HAMPARAN PERAK', 'keterangan' => 'HAMPARAN PERAK', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI', 'keterangan' => 'JL. BINJAI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KABANJAHE', 'keterangan' => 'KABANJAHE', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAMPUNG LALANG', 'keterangan' => 'KAMPUNG LALANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KISARAN', 'keterangan' => 'KISARAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KOTA', 'keterangan' => 'KOTA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KUALA GUMIT', 'keterangan' => 'KUALA GUMIT', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KUALA TANJUNG', 'keterangan' => 'KUALA TANJUNG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LABUHAN', 'keterangan' => 'LABUHAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LANGKAT', 'keterangan' => 'LANGKAT', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LANGSA', 'keterangan' => 'LANGSA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LHOKSEUMAWE', 'keterangan' => 'LHOKSEUMAWE', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LIMA PULUH', 'keterangan' => 'LIMA PULUH', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LUBUK PAKAM', 'keterangan' => 'LUBUK PAKAM', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MANDAILING NATAL', 'keterangan' => 'MANDAILING NATAL', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MANDALA', 'keterangan' => 'MANDALA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MEULABOH', 'keterangan' => 'MEULABOH', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MKT BELAWAN', 'keterangan' => 'MKT BELAWAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PADANG SIDEMPUAN', 'keterangan' => 'PADANG SIDEMPUAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PALEMBANG', 'keterangan' => 'PALEMBANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCING', 'keterangan' => 'PANCING', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCUR BATU', 'keterangan' => 'PANCUR BATU', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANGAKALAN BRANDAN', 'keterangan' => 'PANGAKALAN BRANDAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANGKALAN SUSU', 'keterangan' => 'PANGKALAN SUSU', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEKAN BARU', 'keterangan' => 'PEKAN BARU', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEMATANG SIANTAR', 'keterangan' => 'PEMATANG SIANTAR', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERBAUNGAN', 'keterangan' => 'PERBAUNGAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERCUT', 'keterangan' => 'PERCUT', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERDAGANGAN', 'keterangan' => 'PERDAGANGAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERKEBUNAN PULAU MANDI', 'keterangan' => 'PERKEBUNAN PULAU MANDI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PORSEA', 'keterangan' => 'PORSEA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PULO BRAYAN', 'keterangan' => 'PULO BRAYAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'RANTAU PRAPAT', 'keterangan' => 'RANTAU PRAPAT', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEI BULUH', 'keterangan' => 'SEI BULUH', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEI RAMPAH', 'keterangan' => 'SEI RAMPAH', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEI SUKA BANDAR TINGGI', 'keterangan' => 'SEI SUKA BANDAR TINGGI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SELAYANG', 'keterangan' => 'SELAYANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SIBOLGA', 'keterangan' => 'SIBOLGA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SIDIKALANG', 'keterangan' => 'SIDIKALANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SIMALUNGUN', 'keterangan' => 'SIMALUNGUN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'STABAT', 'keterangan' => 'STABAT', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG BALAI', 'keterangan' => 'TANJUNG BALAI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG PURA', 'keterangan' => 'TANJUNG PURA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TARUTUNG', 'keterangan' => 'TARUTUNG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI', 'keterangan' => 'TEBING TINGGI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TITIPAPAN', 'keterangan' => 'TITIPAPAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'ACEH (PT. ARUN)', 'keterangan' => 'ACEH (PT. ARUN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'ACEH SUBULUSSALAM (PT.BINA PRATAMA PERSADA)', 'keterangan' => 'ACEH SUBULUSSALAM (PT.BINA PRATAMA PERSADA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'ACEH UTARA (DAIKIN APPLLIED S)', 'keterangan' => 'ACEH UTARA (DAIKIN APPLLIED S)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'ACEH UTARA (JAYA TRADE)', 'keterangan' => 'ACEH UTARA (JAYA TRADE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (BINTANG BELAWAN)', 'keterangan' => 'AMPLAS (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (BPE)', 'keterangan' => 'AMPLAS (BPE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (CAB)', 'keterangan' => 'AMPLAS (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (DUTA BINTANG PERKASA)', 'keterangan' => 'AMPLAS (DUTA BINTANG PERKASA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (JBE)', 'keterangan' => 'AMPLAS (JBE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/CV.MULIA UTAMA)', 'keterangan' => 'AMPLAS (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/CV.MULIA UTAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (S/D POLDASU) ASIA SAKTI WAHID FOOD)', 'keterangan' => 'AMPLAS (S/D POLDASU) ASIA SAKTI WAHID FOOD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (SAMUDERA RAYA BERJAYA)', 'keterangan' => 'AMPLAS (SAMUDERA RAYA BERJAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AMPLAS (SMM)', 'keterangan' => 'AMPLAS (SMM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'AROMA MEGA SARI (BREAKBULK)', 'keterangan' => 'AROMA MEGA SARI (BREAKBULK)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BALIGE (HOTEL LABERSA)', 'keterangan' => 'BALIGE (HOTEL LABERSA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BALIGE (PT.PEJANTEN JAYA ABADI)', 'keterangan' => 'BALIGE (PT.PEJANTEN JAYA ABADI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (AMAZONE)', 'keterangan' => 'BANDA ACEH (AMAZONE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (KOPERASI KAN JABUNG/BPTU - HPT INDRAPURI)', 'keterangan' => 'BANDA ACEH (KOPERASI KAN JABUNG/BPTU - HPT INDRAPURI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (MITRA NIAGA)', 'keterangan' => 'BANDA ACEH (MITRA NIAGA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PADI FLOUR NUSANTARA)', 'keterangan' => 'BANDA ACEH (PADI FLOUR NUSANTARA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PANEL ASRI)', 'keterangan' => 'BANDA ACEH (PANEL ASRI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PD. SINAR MAS)', 'keterangan' => 'BANDA ACEH (PD. SINAR MAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PT. CARGILL)', 'keterangan' => 'BANDA ACEH (PT. CARGILL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PT.FOSROC)', 'keterangan' => 'BANDA ACEH (PT.FOSROC)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PT.INDACO WARNA DUNIA)', 'keterangan' => 'BANDA ACEH (PT.INDACO WARNA DUNIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PT.PARAMOUNT  BED INDONESIA)', 'keterangan' => 'BANDA ACEH (PT.PARAMOUNT  BED INDONESIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (PT.SARANA ACEH UTAMA)', 'keterangan' => 'BANDA ACEH (PT.SARANA ACEH UTAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH (SINAR ANTJOL)', 'keterangan' => 'BANDA ACEH (SINAR ANTJOL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BANDA ACEH-BIREUN (JAYA TRADE)', 'keterangan' => 'BANDA ACEH-BIREUN (JAYA TRADE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BELAWAN (TRIROYAL)', 'keterangan' => 'BELAWAN (TRIROYAL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BGR PAYA PASIR', 'keterangan' => 'BGR PAYA PASIR', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI ((PT.YUMEIDA UTAMA/SJ TASIK & SAPTA JAYA (JOGYA)))', 'keterangan' => 'BINJAI ((PT.YUMEIDA UTAMA/SJ TASIK & SAPTA JAYA (JOGYA)))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI (EKO SETIYATNO)', 'keterangan' => 'BINJAI (EKO SETIYATNO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI (GEROBAK - ROBIN WIJAYA)', 'keterangan' => 'BINJAI (GEROBAK - ROBIN WIJAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI (GEROBAK (PT.YUMEIDA UTAMA/BANDAR BARU BOGOR))', 'keterangan' => 'BINJAI (GEROBAK (PT.YUMEIDA UTAMA/BANDAR BARU BOGOR))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI (PT.SARI MURNI PRATAMA)', 'keterangan' => 'BINJAI (PT.SARI MURNI PRATAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BINJAI (ROBIN WIJAYA)', 'keterangan' => 'BINJAI (ROBIN WIJAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BIREUN&BANDA ACEH (PANEL ASRI)', 'keterangan' => 'BIREUN&BANDA ACEH (PANEL ASRI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAHRANG (CML)', 'keterangan' => 'BRAHRANG (CML)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAHRANG (DUNIA PARABOLA)', 'keterangan' => 'BRAHRANG (DUNIA PARABOLA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAHRANG (IBU LIE-LIE)', 'keterangan' => 'BRAHRANG (IBU LIE-LIE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAHRANG (PT. CIPTA MAPAN L)', 'keterangan' => 'BRAHRANG (PT. CIPTA MAPAN L)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRAHRANG (PT.BTS)', 'keterangan' => 'BRAHRANG (PT.BTS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRASTAGI (PT.GARUDA FOOD PUTRA PUTRI JAYA)', 'keterangan' => 'BRASTAGI (PT.GARUDA FOOD PUTRA PUTRI JAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BRASTAGI (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/CV.KARYA BUMI BERSAMA)', 'keterangan' => 'BRASTAGI (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/CV.KARYA BUMI BERSAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'BROHOL T.TINGGI (UD SERASI JY)', 'keterangan' => 'BROHOL T.TINGGI (UD SERASI JY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CANANG ()', 'keterangan' => 'CANANG ()', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CANANG (EXPORT)', 'keterangan' => 'CANANG (EXPORT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CANANG (IMPORT)', 'keterangan' => 'CANANG (IMPORT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CANANG (PACIFIC GLOBAL MAKMUR/OL)', 'keterangan' => 'CANANG (PACIFIC GLOBAL MAKMUR/OL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CEMARA (BINTANG BELAWAN)', 'keterangan' => 'CEMARA (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'CIKAMPAK (PT.TASIK RAJA)', 'keterangan' => 'CIKAMPAK (PT.TASIK RAJA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'DAIRI (PT SEPSACO MANDIRI)', 'keterangan' => 'DAIRI (PT SEPSACO MANDIRI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'DAMULI (ANDI WIJAYA-BERAS)', 'keterangan' => 'DAMULI (ANDI WIJAYA-BERAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'DUMAI (LAHAN HIJAU SEMESTA R)', 'keterangan' => 'DUMAI (LAHAN HIJAU SEMESTA R)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'EXPORT LANGSIR', 'keterangan' => 'EXPORT LANGSIR', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'GAHAPI (GEROBAK)', 'keterangan' => 'GAHAPI (GEROBAK)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HELVETIA (CAB)', 'keterangan' => 'HELVETIA (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HELVETIA (JUMA)', 'keterangan' => 'HELVETIA (JUMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HELVETIA (MERRY)', 'keterangan' => 'HELVETIA (MERRY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'HELVETIA (PT. JAYA PONDASI)', 'keterangan' => 'HELVETIA (PT. JAYA PONDASI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL BINJAI (PT PIGURA J-EXPORT)', 'keterangan' => 'JL BINJAI (PT PIGURA J-EXPORT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. AR HAKIM (SENTRALAND/PERUM', 'keterangan' => 'JL. AR HAKIM (SENTRALAND/PERUM', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (BINTANG BELAWAN)', 'keterangan' => 'JL. BINJAI (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (BP.SOHIR)', 'keterangan' => 'JL. BINJAI (BP.SOHIR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (CAB)', 'keterangan' => 'JL. BINJAI (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (CV. LAUTAN REZEKI)', 'keterangan' => 'JL. BINJAI (CV. LAUTAN REZEKI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (GEROBAK CAB)', 'keterangan' => 'JL. BINJAI (GEROBAK CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (INDOCAFCO)', 'keterangan' => 'JL. BINJAI (INDOCAFCO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (KOTA (CAB))', 'keterangan' => 'JL. BINJAI (KOTA (CAB))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (KUDA LAUT-BP AMIN)', 'keterangan' => 'JL. BINJAI (KUDA LAUT-BP AMIN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. CATUR MITRA SEJATI SENTOSA)', 'keterangan' => 'JL. BINJAI (PT. CATUR MITRA SEJATI SENTOSA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. HOKINDA CITRA', 'keterangan' => 'JL. BINJAI (PT. HOKINDA CITRA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. JASA SUMBER)', 'keterangan' => 'JL. BINJAI (PT. JASA SUMBER)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. MULTI DJASA S)', 'keterangan' => 'JL. BINJAI (PT. MULTI DJASA S)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. PASIAT MARTUA)', 'keterangan' => 'JL. BINJAI (PT. PASIAT MARTUA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. PASIFIK)', 'keterangan' => 'JL. BINJAI (PT. PASIFIK)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. ROPETAMA)', 'keterangan' => 'JL. BINJAI (PT. ROPETAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (PT. SUMATERA KARTINDO)', 'keterangan' => 'JL. BINJAI (PT. SUMATERA KARTINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL. BINJAI (SILKARGO EMPTY)', 'keterangan' => 'JL. BINJAI (SILKARGO EMPTY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'JL.BINJAI', 'keterangan' => 'JL.BINJAI', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. PUTIH (JBE)', 'keterangan' => 'K. PUTIH (JBE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. PUTIH (SILKARGO)', 'keterangan' => 'K. PUTIH (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. PUTIH (SMM)', 'keterangan' => 'K. PUTIH (SMM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. PUTIH (SUNGAI BUDI)', 'keterangan' => 'K. PUTIH (SUNGAI BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. PUTIH (SURYA MAKMUR)', 'keterangan' => 'K. PUTIH (SURYA MAKMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K. TANJUNG', 'keterangan' => 'K. TANJUNG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'K.TANJUNG (PT. SUMIDEN)', 'keterangan' => 'K.TANJUNG (PT. SUMIDEN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KABANJAHE (MITRA NIAGA)', 'keterangan' => 'KABANJAHE (MITRA NIAGA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KABANJAHE (PANEL ASRI)', 'keterangan' => 'KABANJAHE (PANEL ASRI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KANDANG', 'keterangan' => 'KANDANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (AGRO CROPS INDONESIA/PT.MOTASA INDONESIA)', 'keterangan' => 'KAYU PUTIH (AGRO CROPS INDONESIA/PT.MOTASA INDONESIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (BINTANG BELAWAN)', 'keterangan' => 'KAYU PUTIH (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (CAB)', 'keterangan' => 'KAYU PUTIH (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (CV.ANUGERAH JAYA)', 'keterangan' => 'KAYU PUTIH (CV.ANUGERAH JAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (CV.SINAR ANUGERAH PERKASA)', 'keterangan' => 'KAYU PUTIH (CV.SINAR ANUGERAH PERKASA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (MAS)', 'keterangan' => 'KAYU PUTIH (MAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KAYU PUTIH (PUTRA GUNA)', 'keterangan' => 'KAYU PUTIH (PUTRA GUNA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (CAB)', 'keterangan' => 'KIM (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (CML)', 'keterangan' => 'KIM (CML)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (CV. SMM)', 'keterangan' => 'KIM (CV. SMM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (CV.SUMATRA PERKASA DAITOMESINDO)', 'keterangan' => 'KIM (CV.SUMATRA PERKASA DAITOMESINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (GARUDA EMAS)', 'keterangan' => 'KIM (GARUDA EMAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (GEROBAK - MEST INDONESIA/GUDANG ROMO SJAA)', 'keterangan' => 'KIM (GEROBAK - MEST INDONESIA/GUDANG ROMO SJAA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (GROWTH SUMATRA)', 'keterangan' => 'KIM (GROWTH SUMATRA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (IBU CALISTA/PT.KARYA AGUNG)', 'keterangan' => 'KIM (IBU CALISTA/PT.KARYA AGUNG)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (INTRACO AGROINDUSTRY)', 'keterangan' => 'KIM (INTRACO AGROINDUSTRY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (KANDANG)', 'keterangan' => 'KIM (KANDANG)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (MAS)', 'keterangan' => 'KIM (MAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PAPERWORKS/BP.DARMAWAN)', 'keterangan' => 'KIM (PAPERWORKS/BP.DARMAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT. CIPTA MAPAN LOGISTIK)', 'keterangan' => 'KIM (PT. CIPTA MAPAN LOGISTIK)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT. INTAN HEVEA INDUSTRY)', 'keterangan' => 'KIM (PT. INTAN HEVEA INDUSTRY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT. PASIAT MARTUA)', 'keterangan' => 'KIM (PT. PASIAT MARTUA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT. SANTANI AGRO PERSADA)', 'keterangan' => 'KIM (PT. SANTANI AGRO PERSADA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT. SBA)', 'keterangan' => 'KIM (PT. SBA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT. TRIJASA PRIMA INT.)', 'keterangan' => 'KIM (PT. TRIJASA PRIMA INT.)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT.BELAWAN JAYA)', 'keterangan' => 'KIM (PT.BELAWAN JAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT.HARI REZEKI)', 'keterangan' => 'KIM (PT.HARI REZEKI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT.MEST INDONESIY/GUDANG MESTINDO)', 'keterangan' => 'KIM (PT.MEST INDONESIY/GUDANG MESTINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (PT.WICAKSANA MAS)', 'keterangan' => 'KIM (PT.WICAKSANA MAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (SAMUDERA RAYA BERJAYA)', 'keterangan' => 'KIM (SAMUDERA RAYA BERJAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (SAMUDERA)', 'keterangan' => 'KIM (SAMUDERA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (SARANA TRANS SUMATERA)', 'keterangan' => 'KIM (SARANA TRANS SUMATERA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (SIL KARGO)', 'keterangan' => 'KIM (SIL KARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (SILKARGO GDG RIKO)', 'keterangan' => 'KIM (SILKARGO GDG RIKO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (UD.SUBUR JAYA/ACAI)', 'keterangan' => 'KIM (UD.SUBUR JAYA/ACAI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM (UNION CONFECTIONERY)', 'keterangan' => 'KIM (UNION CONFECTIONERY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM ALING MSP', 'keterangan' => 'KIM ALING MSP', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM III (LANGSIR MSI)', 'keterangan' => 'KIM III (LANGSIR MSI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM JUISHIN (JKT, SBY)', 'keterangan' => 'KIM JUISHIN (JKT, SBY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KIM P.BUTON MSP', 'keterangan' => 'KIM P.BUTON MSP', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KISARAN (BP.HERI)', 'keterangan' => 'KISARAN (BP.HERI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KISARAN (GEROBAK - PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI)', 'keterangan' => 'KISARAN (GEROBAK - PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KISARAN (PT GRAHA MITRA-JAGUNG', 'keterangan' => 'KISARAN (PT GRAHA MITRA-JAGUNG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KISARAN (PT.GARUDA FOOD PUTRA PUTRI JAYA)', 'keterangan' => 'KISARAN (PT.GARUDA FOOD PUTRA PUTRI JAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KISARAN (SUNGAI BUDI)', 'keterangan' => 'KISARAN (SUNGAI BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KOTA (CAB)', 'keterangan' => 'KOTA (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KOTA BANGUN (BINTANG BELAWAN)', 'keterangan' => 'KOTA BANGUN (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KP.LALANG', 'keterangan' => 'KP.LALANG', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU (BINTANG BELAWAN)', 'keterangan' => 'KRAKATAU (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU (GEROBAK - ERNAWATY SITOHANG/BP.TONI)', 'keterangan' => 'KRAKATAU (GEROBAK - ERNAWATY SITOHANG/BP.TONI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU (PT. MAJU BERSAMA DRIVINDO)', 'keterangan' => 'KRAKATAU (PT. MAJU BERSAMA DRIVINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU (SILKARGO)', 'keterangan' => 'KRAKATAU (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU (SMM)', 'keterangan' => 'KRAKATAU (SMM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KRAKATAU/METAL (GARUDA EMAS)', 'keterangan' => 'KRAKATAU/METAL (GARUDA EMAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'KUALA GUMIT (SETIA BUDI)', 'keterangan' => 'KUALA GUMIT (SETIA BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LABUHAN (BINTANG BELAWAN)', 'keterangan' => 'LABUHAN (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LANGKAT (HASANUDIN/ERWARD)', 'keterangan' => 'LANGKAT (HASANUDIN/ERWARD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LANGKAT (PT. LEMBU ANDALAS LANGKAT)', 'keterangan' => 'LANGKAT (PT. LEMBU ANDALAS LANGKAT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LANGKAT (PT.SARANA METAL INDAH)', 'keterangan' => 'LANGKAT (PT.SARANA METAL INDAH)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LANGSIR PELABUHAN', 'keterangan' => 'LANGSIR PELABUHAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LHOKSEUMAWE (NUTRIFOOD)', 'keterangan' => 'LHOKSEUMAWE (NUTRIFOOD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LHOKSEUMAWE (PT.KABEL METAL I)', 'keterangan' => 'LHOKSEUMAWE (PT.KABEL METAL I)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LHOKSEUMAWE (PUPUK ISKANDAR M)', 'keterangan' => 'LHOKSEUMAWE (PUPUK ISKANDAR M)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'LUBUK PAKAM (PT.SALIM IVOMAS PRATAMA)', 'keterangan' => 'LUBUK PAKAM (PT.SALIM IVOMAS PRATAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR (BINTANG BELAWAN)', 'keterangan' => 'MABAR (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR (CML)', 'keterangan' => 'MABAR (CML)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR (JBE)', 'keterangan' => 'MABAR (JBE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR (PT. SUBUR MAKMUR S)', 'keterangan' => 'MABAR (PT. SUBUR MAKMUR S)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR (SILKARGO)', 'keterangan' => 'MABAR (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MABAR (WIRADWIKA)', 'keterangan' => 'MABAR (WIRADWIKA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MALAHAYATI ACEH (PT JAYA TRADE', 'keterangan' => 'MALAHAYATI ACEH (PT JAYA TRADE', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MANDALA (BP. AHOK)', 'keterangan' => 'MANDALA (BP. AHOK)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MANDALA (GEROBAK (BP.APIN/PT.GMA))', 'keterangan' => 'MANDALA (GEROBAK (BP.APIN/PT.GMA))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MANDALA/TEMBUNG (BP. APIN)', 'keterangan' => 'MANDALA/TEMBUNG (BP. APIN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MARELAN (CV. REZEKI BERSAMA)', 'keterangan' => 'MARELAN (CV. REZEKI BERSAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MEULABOH (CHUANGUI KONSTRUKSI INDONESIA)', 'keterangan' => 'MEULABOH (CHUANGUI KONSTRUKSI INDONESIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MEULABOH (GROBEST)', 'keterangan' => 'MEULABOH (GROBEST)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'MMTC PANCING (INDO TEKNIK T)', 'keterangan' => 'MMTC PANCING (INDO TEKNIK T)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAD (PT. FOSROC)', 'keterangan' => 'NAD (PT. FOSROC)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE (DUTA AYU MAS)', 'keterangan' => 'NAMORAMBE (DUTA AYU MAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE (PT.BINA CAKRA MANDIRI)', 'keterangan' => 'NAMORAMBE (PT.BINA CAKRA MANDIRI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE (PT.BINTANG PERSADA SATELIT)', 'keterangan' => 'NAMORAMBE (PT.BINTANG PERSADA SATELIT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE (PT.MEKADA ABADI)', 'keterangan' => 'NAMORAMBE (PT.MEKADA ABADI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE (PT.SHAMROCK MANUFACTURING CORPORA/PT.HALONI JANE)', 'keterangan' => 'NAMORAMBE (PT.SHAMROCK MANUFACTURING CORPORA/PT.HALONI JANE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMORAMBE (SINDOGLOBAL GEROBAK)', 'keterangan' => 'NAMORAMBE (SINDOGLOBAL GEROBAK)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'NAMURAMBE', 'keterangan' => 'NAMURAMBE', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P. BRAYAN', 'keterangan' => 'P. BRAYAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P. BULAN', 'keterangan' => 'P. BULAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P. SIANTAR', 'keterangan' => 'P. SIANTAR', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P. SIANTAR (SUNGAI BUDI)', 'keterangan' => 'P. SIANTAR (SUNGAI BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P. SIDEMPUAN (TRONTON)', 'keterangan' => 'P. SIDEMPUAN (TRONTON)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P.BRANDAN', 'keterangan' => 'P.BRANDAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'P.SIDEMPUAN (GARUDA FOOD/SNS)', 'keterangan' => 'P.SIDEMPUAN (GARUDA FOOD/SNS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCING (PABRIK KERUPUK INDOSARI/TOKO BINTANG TIMUR)', 'keterangan' => 'PANCING (PABRIK KERUPUK INDOSARI/TOKO BINTANG TIMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCING (SILKARGO)', 'keterangan' => 'PANCING (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCING (SURYAPLASINDO UNGGUL PERKASA)', 'keterangan' => 'PANCING (SURYAPLASINDO UNGGUL PERKASA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCUR BATU (BINTANG BELAWAN)', 'keterangan' => 'PANCUR BATU (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANCUR BATU (CML)', 'keterangan' => 'PANCUR BATU (CML)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANGKALAN SUSU (JL.LANGSA-PT.TJAKRINDO MAS )', 'keterangan' => 'PANGKALAN SUSU (JL.LANGSA-PT.TJAKRINDO MAS )', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANTAI LABU', 'keterangan' => 'PANTAI LABU', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PANTAI LABU (BP.HERI)', 'keterangan' => 'PANTAI LABU (BP.HERI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PATUMBAK (PT. MKT)', 'keterangan' => 'PATUMBAK (PT. MKT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PAYA PASIR (BINTANG BELAWAN)', 'keterangan' => 'PAYA PASIR (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEKANBARU (SUNWAY)', 'keterangan' => 'PEKANBARU (SUNWAY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEKANBARU (TATA LOGAM LESTARI)', 'keterangan' => 'PEKANBARU (TATA LOGAM LESTARI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEMATANG SIANTAR ((PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI))', 'keterangan' => 'PEMATANG SIANTAR ((PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEMATANG SIANTAR (BP. WILSON)', 'keterangan' => 'PEMATANG SIANTAR (BP. WILSON)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEMATANG SIANTAR (CV.BONAR JAYA ADIPERKASA)', 'keterangan' => 'PEMATANG SIANTAR (CV.BONAR JAYA ADIPERKASA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PEMATANG SIANTAR (PT.GARUDA FOOD PUTRA PUTRI JAYA)', 'keterangan' => 'PEMATANG SIANTAR (PT.GARUDA FOOD PUTRA PUTRI JAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERCUT (GEROBAK - PT.UNION)', 'keterangan' => 'PERCUT (GEROBAK - PT.UNION)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERCUT (PT.UNION)', 'keterangan' => 'PERCUT (PT.UNION)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'PERDAGANGAN (PT. MITRA PEMUDA)', 'keterangan' => 'PERDAGANGAN (PT. MITRA PEMUDA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'RANTAU PRAPAT (AMAZONE)', 'keterangan' => 'RANTAU PRAPAT (AMAZONE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'RANTAU PRAPAT (GARUDA FOOD)', 'keterangan' => 'RANTAU PRAPAT (GARUDA FOOD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'RANTAU PRAPAT (PT.CHRONOS UNIVERSAL)', 'keterangan' => 'RANTAU PRAPAT (PT.CHRONOS UNIVERSAL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (BINTANG BELAWAN)', 'keterangan' => 'SAMPALI (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (BP.TONY/GD.KARTIKA BHUANA NIAGA)', 'keterangan' => 'SAMPALI (BP.TONY/GD.KARTIKA BHUANA NIAGA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (BP.TONY/GD.SIRIE)', 'keterangan' => 'SAMPALI (BP.TONY/GD.SIRIE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (CAB)', 'keterangan' => 'SAMPALI (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (EKO SETIYATNO/PT.TIMUR RAYA TUNGGAL)', 'keterangan' => 'SAMPALI (EKO SETIYATNO/PT.TIMUR RAYA TUNGGAL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (EKO SETIYATNO/TEKNIK KIMIA NUSANTARA)', 'keterangan' => 'SAMPALI (EKO SETIYATNO/TEKNIK KIMIA NUSANTARA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (GEROBAK - PAPERWORKS/HENDRI LUSLY)', 'keterangan' => 'SAMPALI (GEROBAK - PAPERWORKS/HENDRI LUSLY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (PT.SINAR SURYA ABADI SEJAHTERA)', 'keterangan' => 'SAMPALI (PT.SINAR SURYA ABADI SEJAHTERA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SAMPALI (SUMIN SURYA SEJAHTERA', 'keterangan' => 'SAMPALI (SUMIN SURYA SEJAHTERA', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SBU', 'keterangan' => 'SBU', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEI RAMPAH (FLORINDO MAKMUR)', 'keterangan' => 'SEI RAMPAH (FLORINDO MAKMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEI RAMPAH (PT. SUNGAI BUDI)', 'keterangan' => 'SEI RAMPAH (PT. SUNGAI BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEI SUKA BANDAR TINGGI (BP. HERI)', 'keterangan' => 'SEI SUKA BANDAR TINGGI (BP. HERI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SEIRAMPAH', 'keterangan' => 'SEIRAMPAH', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SETIA JADI (MR HARYANTO)', 'keterangan' => 'SETIA JADI (MR HARYANTO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SINDOGLOBAL (GEROBAK LANGSIR)', 'keterangan' => 'SINDOGLOBAL (GEROBAK LANGSIR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SP. KANTOR', 'keterangan' => 'SP. KANTOR', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'STABAT (SUNGAI BUDI)', 'keterangan' => 'STABAT (SUNGAI BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUBULUSSALAM-B.ACEH (JAYA TRAD', 'keterangan' => 'SUBULUSSALAM-B.ACEH (JAYA TRAD', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (BINTANG BELAWAN)', 'keterangan' => 'SUNGGAL (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (BP.FELIX/BP.VINCENT)', 'keterangan' => 'SUNGGAL (BP.FELIX/BP.VINCENT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (BP.SOHIR)', 'keterangan' => 'SUNGGAL (BP.SOHIR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (GEROBAK - PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI)', 'keterangan' => 'SUNGGAL (GEROBAK - PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (KHARISMA)', 'keterangan' => 'SUNGGAL (KHARISMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (PT. PRIMKOPAD SENA)', 'keterangan' => 'SUNGGAL (PT. PRIMKOPAD SENA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (PT.SUBUR BAJA PRATAMA/UD.SUBUR/ACAI)', 'keterangan' => 'SUNGGAL (PT.SUBUR BAJA PRATAMA/UD.SUBUR/ACAI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'SUNGGAL (SJL)', 'keterangan' => 'SUNGGAL (SJL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'T.KENAS (PT.TANJUNG KH/B.AGUAN', 'keterangan' => 'T.KENAS (PT.TANJUNG KH/B.AGUAN', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'T.TINGGI (SNS GARUDA FOOD)', 'keterangan' => 'T.TINGGI (SNS GARUDA FOOD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAKENGON (PT.KBQ BABURRAYYAN)', 'keterangan' => 'TAKENGON (PT.KBQ BABURRAYYAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAKENGON ACEH (JAYA TRADE)', 'keterangan' => 'TAKENGON ACEH (JAYA TRADE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA (AROMA MEGA SARI)', 'keterangan' => 'TAMORA (AROMA MEGA SARI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA (INDO KENCANA SATERIA)', 'keterangan' => 'TAMORA (INDO KENCANA SATERIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA (PT TRIMAS KEMASINDO S)', 'keterangan' => 'TAMORA (PT TRIMAS KEMASINDO S)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA (PT. CIPTA MAPAN LOG)', 'keterangan' => 'TAMORA (PT. CIPTA MAPAN LOG)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TAMORA (SURYA ALAMINDO MAKMUR)', 'keterangan' => 'TAMORA (SURYA ALAMINDO MAKMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANDEM (BAMINDO AGRA PERSADA/BP.ANDI/IWAN)', 'keterangan' => 'TANDEM (BAMINDO AGRA PERSADA/BP.ANDI/IWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANDEM (DEKORINDO PRATAMA/DEPO 78)', 'keterangan' => 'TANDEM (DEKORINDO PRATAMA/DEPO 78)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANDEM (PAK CIU HUAT/JONLY)', 'keterangan' => 'TANDEM (PAK CIU HUAT/JONLY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANDEM (PANGABEAN/ETERNA JAYA)', 'keterangan' => 'TANDEM (PANGABEAN/ETERNA JAYA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANDEM (PT. RUSINDO PRIMA)', 'keterangan' => 'TANDEM (PT. RUSINDO PRIMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG BALAI (PT. SREE INTERNATIONAL INDO)', 'keterangan' => 'TANJUNG BALAI (PT. SREE INTERNATIONAL INDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG BALAI (PT.AGRINDO A)', 'keterangan' => 'TANJUNG BALAI (PT.AGRINDO A)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG BALAI (SOLVAY SODI AD)', 'keterangan' => 'TANJUNG BALAI (SOLVAY SODI AD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA ((PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI))', 'keterangan' => 'TANJUNG MORAWA ((PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (AROMA MEGA SARI)', 'keterangan' => 'TANJUNG MORAWA (AROMA MEGA SARI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (BINTANG BELAWAN)', 'keterangan' => 'TANJUNG MORAWA (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (BP.GUNAWAN/BP.RUDI/SURYA MAKMUR)', 'keterangan' => 'TANJUNG MORAWA (BP.GUNAWAN/BP.RUDI/SURYA MAKMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (BP.PAU SEN/PT.KHARISMA)', 'keterangan' => 'TANJUNG MORAWA (BP.PAU SEN/PT.KHARISMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (CML)', 'keterangan' => 'TANJUNG MORAWA (CML)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (DEKORINDO PRATAMA/RIMBA KENCANA)', 'keterangan' => 'TANJUNG MORAWA (DEKORINDO PRATAMA/RIMBA KENCANA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (FORTA MEGAH SEJATI/MUHAMMAD ARIF ARIFIN/PT.FNB INDONESIA)', 'keterangan' => 'TANJUNG MORAWA (FORTA MEGAH SEJATI/MUHAMMAD ARIF ARIFIN/PT.FNB INDONESIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (GEROBAK - FORTA MEGAH SEJATI/JULI/JACKSON THERESIA)', 'keterangan' => 'TANJUNG MORAWA (GEROBAK - FORTA MEGAH SEJATI/JULI/JACKSON THERESIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (GEROBAK (BP.PAU SEN/BP.WANG))', 'keterangan' => 'TANJUNG MORAWA (GEROBAK (BP.PAU SEN/BP.WANG))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (IBU AYEN)', 'keterangan' => 'TANJUNG MORAWA (IBU AYEN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (NG TJIN TJIN/SINAR ALINDO CIKANDE & BABETINDO)', 'keterangan' => 'TANJUNG MORAWA (NG TJIN TJIN/SINAR ALINDO CIKANDE & BABETINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT. HST)', 'keterangan' => 'TANJUNG MORAWA (PT. HST)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT. NEW HOPE MEDAN)', 'keterangan' => 'TANJUNG MORAWA (PT. NEW HOPE MEDAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT.INDO BATAM EKATAMA)', 'keterangan' => 'TANJUNG MORAWA (PT.INDO BATAM EKATAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT.MAJU JAYA POHON PINANG/PT.MAJU BERSAMA )', 'keterangan' => 'TANJUNG MORAWA (PT.MAJU JAYA POHON PINANG/PT.MAJU BERSAMA )', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT.MAJU JAYA POHON PINANG/PT.MAJU BERSAMA)', 'keterangan' => 'TANJUNG MORAWA (PT.MAJU JAYA POHON PINANG/PT.MAJU BERSAMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT.PETNESIA RESINDO/PT.BUANA PRIMA KEMASINDO)', 'keterangan' => 'TANJUNG MORAWA (PT.PETNESIA RESINDO/PT.BUANA PRIMA KEMASINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT.UNION)', 'keterangan' => 'TANJUNG MORAWA (PT.UNION)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/CV.PERMATA DELI MAKMUR)', 'keterangan' => 'TANJUNG MORAWA (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/CV.PERMATA DELI MAKMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (REY IMPORT)', 'keterangan' => 'TANJUNG MORAWA (REY IMPORT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (SARANG TAWON)', 'keterangan' => 'TANJUNG MORAWA (SARANG TAWON)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (SILKARGO)', 'keterangan' => 'TANJUNG MORAWA (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (SUNGAI BUDI)', 'keterangan' => 'TANJUNG MORAWA (SUNGAI BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MORAWA (TANJUNG MORAWA)', 'keterangan' => 'TANJUNG MORAWA (TANJUNG MORAWA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (BINTANG BELAWAN)', 'keterangan' => 'TANJUNG MULIA (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (BP.ASIM)', 'keterangan' => 'TANJUNG MULIA (BP.ASIM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (BP.RUDI)', 'keterangan' => 'TANJUNG MULIA (BP.RUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (CAB)', 'keterangan' => 'TANJUNG MULIA (CAB)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (GEROBAK (PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI))', 'keterangan' => 'TANJUNG MULIA (GEROBAK (PT. SUBUR BAJA PRATAMA/UD.SUBUR/ACAI))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (KHARISMA)', 'keterangan' => 'TANJUNG MULIA (KHARISMA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (NIPPON PAINT)', 'keterangan' => 'TANJUNG MULIA (NIPPON PAINT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (PASIFIK GLOBAL)', 'keterangan' => 'TANJUNG MULIA (PASIFIK GLOBAL)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (SILKARGO)', 'keterangan' => 'TANJUNG MULIA (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (SMM)', 'keterangan' => 'TANJUNG MULIA (SMM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (UNIVERSAL INDOFOOD PRODUCT)', 'keterangan' => 'TANJUNG MULIA (UNIVERSAL INDOFOOD PRODUCT)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TANJUNG MULIA (WAHANA TIRTA SARI (GEROBAK))', 'keterangan' => 'TANJUNG MULIA (WAHANA TIRTA SARI (GEROBAK))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TARUTUNG (PT.MEDICAL IMAGING INDONESIA)', 'keterangan' => 'TARUTUNG (PT.MEDICAL IMAGING INDONESIA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI ((PT.ANEKA GAS INDUSTRI/RSUD DR H KUMPULAN PANE))', 'keterangan' => 'TEBING TINGGI ((PT.ANEKA GAS INDUSTRI/RSUD DR H KUMPULAN PANE))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI (BP.HERI)', 'keterangan' => 'TEBING TINGGI (BP.HERI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI (BP.NURSAM NURDIN)', 'keterangan' => 'TEBING TINGGI (BP.NURSAM NURDIN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI (CV.BONAR JAYA ADIPERKASA)', 'keterangan' => 'TEBING TINGGI (CV.BONAR JAYA ADIPERKASA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI (MULTI JASA S)', 'keterangan' => 'TEBING TINGGI (MULTI JASA S)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI (SETIA BUDI)', 'keterangan' => 'TEBING TINGGI (SETIA BUDI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEBING TINGGI (SUTAN FIRMAN)', 'keterangan' => 'TEBING TINGGI (SUTAN FIRMAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (BINTANG BELAWAN)', 'keterangan' => 'TEMBUNG (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (BP HENRY)', 'keterangan' => 'TEMBUNG (BP HENRY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (BP. ACHING)', 'keterangan' => 'TEMBUNG (BP. ACHING)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (BP. AWEI)', 'keterangan' => 'TEMBUNG (BP. AWEI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (BP. SIMAMORA)', 'keterangan' => 'TEMBUNG (BP. SIMAMORA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (CML)', 'keterangan' => 'TEMBUNG (CML)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (ERA GRAHA)', 'keterangan' => 'TEMBUNG (ERA GRAHA)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (GEROBAK (UD.SUBUR/ACAI))', 'keterangan' => 'TEMBUNG (GEROBAK (UD.SUBUR/ACAI))', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (HENNY)', 'keterangan' => 'TEMBUNG (HENNY)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (IRWAN)', 'keterangan' => 'TEMBUNG (IRWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (JBE)', 'keterangan' => 'TEMBUNG (JBE)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (NG TJIN TJIN/SINAR ALINDO CIKANDE & BABETINDO)', 'keterangan' => 'TEMBUNG (NG TJIN TJIN/SINAR ALINDO CIKANDE & BABETINDO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (PT.CENTRAL MANDIRI CEMERLANG)', 'keterangan' => 'TEMBUNG (PT.CENTRAL MANDIRI CEMERLANG)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (PT.WICAKSANA MAS)', 'keterangan' => 'TEMBUNG (PT.WICAKSANA MAS)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/PT.ADAM DANI LESTARI)', 'keterangan' => 'TEMBUNG (PT.YCH INDONESIA (FFI/ SUSU BENDERA)/PT.ADAM DANI LESTARI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (SILKARGO)', 'keterangan' => 'TEMBUNG (SILKARGO)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (SMM)', 'keterangan' => 'TEMBUNG (SMM)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (UD SUBUR/ACAI)', 'keterangan' => 'TEMBUNG (UD SUBUR/ACAI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TEMBUNG (UD.SUBUR/BP.ACAI)', 'keterangan' => 'TEMBUNG (UD.SUBUR/BP.ACAI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TG MULIA (INDUSTRI KARET DELI)', 'keterangan' => 'TG MULIA (INDUSTRI KARET DELI)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'THAMRIN PLAZA (BCD)', 'keterangan' => 'THAMRIN PLAZA (BCD)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TITIPAPAN (BINTANG BELAWAN)', 'keterangan' => 'TITIPAPAN (BINTANG BELAWAN)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'TITIPAPAN (BP.GUNAWAN/BP.RUDI/SURYA MAKMUR)', 'keterangan' => 'TITIPAPAN (BP.GUNAWAN/BP.RUDI/SURYA MAKMUR)', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
        kota::create(['kodekota' => 'WARUNA LANGSIR DEPO', 'keterangan' => 'WARUNA LANGSIR DEPO', 'zona_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'RYAN',]);
    }
}
