<?php

namespace Database\Seeders;

<<<<<<< HEAD
use App\Models\Menu;
=======
>>>>>>> 2a180d1c8113d21ff9e5eb8d26b0e92eeedc32c0
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
<<<<<<< HEAD
        $menus = [
            [
                'menuname' => 'Home',
                'menuseq' => '10',
                'menuparent' => '0',
                'menuicon' => 'fas fa-home',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => 'dashboard',
                'menukode' => '0',
            ],
            [
                'menuname' => 'Logout',
                'menuseq' => '90',
                'menuparent' => '0',
                'menuicon' => 'icon-out',
                'aco_id' => '5',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => 'logout',
                'menukode' => '9',
            ],
            [
                'menuname' => 'Master',
                'menuseq' => '20',
                'menuparent' => '0',
                'menuicon' => 'fas fa-list',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '1',
            ],
            [
                'menuname' => 'User',
                'menuseq' => '20',
                'menuparent' => '5',
                'menuicon' => 'fas fa-user',
                'aco_id' => '1',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '161',
            ],
            [
                'menuname' => 'System',
                'menuseq' => '100',
                'menuparent' => '3',
                'menuicon' => 'fab fa-ubuntu',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '16',
            ],
            [
                'menuname' => 'Role',
                'menuseq' => '30',
                'menuparent' => '5',
                'menuicon' => 'fas fa-user-tag',
                'aco_id' => '6',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '162',
            ],
            [
                'menuname' => 'Menu',
                'menuseq' => '31',
                'menuparent' => '5',
                'menuicon' => 'fas fa-bars',
                'aco_id' => '10',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '163',
            ],
            [
                'menuname' => 'Parameter',
                'menuseq' => '32',
                'menuparent' => '5',
                'menuicon' => 'fas fa-exclamation',
                'aco_id' => '14',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '164',
            ],
            [
                'menuname' => 'User Role',
                'menuseq' => '33',
                'menuparent' => '5',
                'menuicon' => 'fas fa-user-tag',
                'aco_id' => '18',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '165',
            ],
            [
                'menuname' => 'User Menu',
                'menuseq' => '34',
                'menuparent' => '5',
                'menuicon' => 'fas fa-user-minus',
                'aco_id' => '22',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '166',
            ],
            [
                'menuname' => 'Error',
                'menuseq' => '35',
                'menuparent' => '5',
                'menuicon' => 'fas fa-bug',
                'aco_id' => '26',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '167',
            ],
            [
                'menuname' => 'Hak Role',
                'menuseq' => '36',
                'menuparent' => '5',
                'menuicon' => 'fas fa-user-tag',
                'aco_id' => '30',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '168',
            ],
            [
                'menuname' => 'Relasi',
                'menuseq' => '100',
                'menuparent' => '3',
                'menuicon' => 'fas fa-people-arrows',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '11',
            ],
            [
                'menuname' => 'General',
                'menuseq' => '100',
                'menuparent' => '3',
                'menuicon' => 'fas fa-clinic-medical',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '12',
            ],
            [
                'menuname' => 'Jurnal Umum',
                'menuseq' => '100',
                'menuparent' => '3',
                'menuicon' => 'fas fa-book',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '13',
            ],
            [
                'menuname' => 'Kas/Bank',
                'menuseq' => '100',
                'menuparent' => '3',
                'menuicon' => 'fas fa-university',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '14',
            ],
            [
                'menuname' => 'Trucking',
                'menuseq' => '100',
                'menuparent' => '3',
                'menuicon' => 'fas fa-truck-moving',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '15',
            ],
            [
                'menuname' => 'Kode Perkiraan',
                'menuseq' => '111',
                'menuparent' => '15',
                'menuicon' => 'fas fa-file-invoice',
                'aco_id' => '34',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '131',
            ],
            [
                'menuname' => 'Cabang',
                'menuseq' => '100',
                'menuparent' => '14',
                'menuicon' => 'fas fa-code-branch',
                'aco_id' => '38',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '121',
            ],
            [
                'menuname' => 'Penerima',
                'menuseq' => '100',
                'menuparent' => '13',
                'menuicon' => 'fas fa-people-carry',
                'aco_id' => '42',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '111',
            ],
            [
                'menuname' => 'Kas Bank',
                'menuseq' => '100',
                'menuparent' => '16',
                'menuicon' => 'fas fa-university',
                'aco_id' => '46',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '141',
            ],
            [
                'menuname' => 'Kas/Bank',
                'menuseq' => '20',
                'menuparent' => '0',
                'menuicon' => 'fas fa-university',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '2',
            ],
            [
                'menuname' => 'Kas Gantung',
                'menuseq' => '100',
                'menuparent' => '22',
                'menuicon' => 'fas fa-weight-hanging',
                'aco_id' => '50',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '21',
            ],
            [
                'menuname' => 'Trado',
                'menuseq' => '100',
                'menuparent' => '17',
                'menuicon' => 'fas fa-truck-moving',
                'aco_id' => '54',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '151',
            ],
            [
                'menuname' => 'Kota',
                'menuseq' => '100',
                'menuparent' => '17',
                'menuicon' => 'fas fa-city',
                'aco_id' => '60',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '152',
            ],
            [
                'menuname' => 'Zona',
                'menuseq' => '111',
                'menuparent' => '17',
                'menuicon' => 'fas fa-grip-horizontal',
                'aco_id' => '64',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '153',
            ],
            [
                'menuname' => 'Emkl',
                'menuseq' => '112',
                'menuparent' => '17',
                'menuicon' => 'fas fa-truck-pickup',
                'aco_id' => '70',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '154',
            ],
            [
                'menuname' => 'Mandor',
                'menuseq' => '1124',
                'menuparent' => '17',
                'menuicon' => 'fas fa-user-alt',
                'aco_id' => '74',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '155',
            ],
            [
                'menuname' => 'Trucking',
                'menuseq' => '100',
                'menuparent' => '0',
                'menuicon' => 'fas fa-truck-moving',
                'aco_id' => '0',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '3',
            ],
            [
                'menuname' => 'Absensi',
                'menuseq' => '100',
                'menuparent' => '29',
                'menuicon' => 'fas fa-walking',
                'aco_id' => '78',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '31',
            ],
            [
                'menuname' => 'Container',
                'menuseq' => '100',
                'menuparent' => '17',
                'menuicon' => 'fa fa-home',
                'aco_id' => '82',
                'modifiedby' => 'admin',
                'link' => '',
                'menuexe' => '',
                'menukode' => '156',
            ]				
        ];
        
        foreach ($menus as $menu ) {
            Menu::create($menu);
        }
=======
        //
>>>>>>> 2a180d1c8113d21ff9e5eb8d26b0e92eeedc32c0
    }
}
