<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PenerimaanTruckingHeader;
use Illuminate\Support\Facades\DB;

class PenerimaanTruckingHeaderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("delete penerimaantruckingheader");
        DB::statement("DBCC CHECKIDENT ('penerimaantruckingheader', RESEED, 1);");

        penerimaantruckingheader::create(['nobukti' => 'DPO 0001/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N ADERIAN VALENTIN YUSUF', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '7', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0002/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N ADY GUNAWAN', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '10', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0003/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N AFRIAN SAMUEL SIMANGUNSONG II', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '12', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0004/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N AMINTON SIMAMORA', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '23', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0005/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N BAYU PAMUNGKAS', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '50', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0006/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N CHANDRA ARIANTO TAMPUBOLON', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '64', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0007/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N DEWANTO PURBA (EX) III', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '76', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0008/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N DIMAS AGUNG PRABOWO', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '77', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0009/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N DOLLIADI', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '81', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0010/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N FAZAR RAHMADAN', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '100', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0011/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N HENDIKA KURNIAWAN', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '123', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0012/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N JANTO', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '158', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0013/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N JULIADI MANURUNG', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '172', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0014/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N LANDO KRISMAN SIREGAR (EX) II', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '183', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0015/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N LIBERTO', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '184', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0016/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N LOVVER REDI TAMPUBOLON (EX)', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '187', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0017/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N M. YUSUF', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '196', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0018/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N M. YUSUF III (EX)', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '198', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0019/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N RAMADANI GINTING', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '260', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0020/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SAHBUDIN', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '285', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0021/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SULAIMAN', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '317', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0022/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SYAFRIZAL', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '325', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0023/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SYAIFUL BAHRI LUBIS', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '327', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
        penerimaantruckingheader::create(['nobukti' => 'DPO 0024/IV/2023', 'tglbukti' => '2023/4/29', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N PENDI', 'penerimaantrucking_id' => '3', 'karyawan_id' => '0', 'bank_id' => '1', 'supir_id' => '331', 'coa' => '01.04.02.01', 'penerimaan_nobukti' => '', 'statusformat' => '125', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'admin',]);
    }
}
