<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PenerimaanTruckingDetail;
use Illuminate\Support\Facades\DB;

class PenerimaanTruckingDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete penerimaantruckingdetail");
        DB::statement("DBCC CHECKIDENT ('penerimaantruckingdetail', RESEED, 1);");

        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '1', 'nobukti' => 'DPO 0001/IV/2023', 'supir_id' => '7', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '2710000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N ADERIAN VALENTIN YUSUF', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '2', 'nobukti' => 'DPO 0002/IV/2023', 'supir_id' => '10', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '25000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N ADY GUNAWAN', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '3', 'nobukti' => 'DPO 0003/IV/2023', 'supir_id' => '12', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '385000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N AFRIAN SAMUEL SIMANGUNSONG II', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '4', 'nobukti' => 'DPO 0004/IV/2023', 'supir_id' => '23', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '480000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N AMINTON SIMAMORA', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '5', 'nobukti' => 'DPO 0005/IV/2023', 'supir_id' => '50', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '25000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N BAYU PAMUNGKAS', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '6', 'nobukti' => 'DPO 0006/IV/2023', 'supir_id' => '64', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '1620000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N CHANDRA ARIANTO TAMPUBOLON', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '7', 'nobukti' => 'DPO 0007/IV/2023', 'supir_id' => '76', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '830000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N DEWANTO PURBA (EX) III', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '8', 'nobukti' => 'DPO 0008/IV/2023', 'supir_id' => '77', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '2950000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N DIMAS AGUNG PRABOWO', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '9', 'nobukti' => 'DPO 0009/IV/2023', 'supir_id' => '81', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '985000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N DOLLIADI', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '10', 'nobukti' => 'DPO 0010/IV/2023', 'supir_id' => '100', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '925000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N FAZAR RAHMADAN', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '11', 'nobukti' => 'DPO 0011/IV/2023', 'supir_id' => '123', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '335000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N HENDIKA KURNIAWAN', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '12', 'nobukti' => 'DPO 0012/IV/2023', 'supir_id' => '158', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '3100773.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N JANTO', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'DPO 0013/IV/2023', 'supir_id' => '172', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '250000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N JULIADI MANURUNG', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '14', 'nobukti' => 'DPO 0014/IV/2023', 'supir_id' => '183', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '955000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N LANDO KRISMAN SIREGAR (EX) II', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '15', 'nobukti' => 'DPO 0015/IV/2023', 'supir_id' => '184', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '4132742.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N LIBERTO', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '16', 'nobukti' => 'DPO 0016/IV/2023', 'supir_id' => '187', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '2330000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N LOVVER REDI TAMPUBOLON (EX)', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '17', 'nobukti' => 'DPO 0017/IV/2023', 'supir_id' => '196', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '580000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N M. YUSUF', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '18', 'nobukti' => 'DPO 0018/IV/2023', 'supir_id' => '198', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '305000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N M. YUSUF III (EX)', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '19', 'nobukti' => 'DPO 0019/IV/2023', 'supir_id' => '260', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '1290000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N RAMADANI GINTING', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '20', 'nobukti' => 'DPO 0020/IV/2023', 'supir_id' => '285', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '5164142.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SAHBUDIN', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '21', 'nobukti' => 'DPO 0021/IV/2023', 'supir_id' => '317', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '4545183.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SULAIMAN', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '22', 'nobukti' => 'DPO 0022/IV/2023', 'supir_id' => '325', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '2850000.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SYAFRIZAL', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '23', 'nobukti' => 'DPO 0023/IV/2023', 'supir_id' => '327', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '3127500.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N SYAIFUL BAHRI LUBIS', 'modifiedby' => 'admin',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '24', 'nobukti' => 'DPO 0024/IV/2023', 'supir_id' => '331', 'karyawan_id' => '0', 'pengeluarantruckingheader_nobukti' => '', 'pengeluaranstokheader_nobukti' => '', 'stok_id' => '0', 'qty' => '0.00', 'nominal' => '4002830.00', 'keterangan' => 'SALDO AWAL DEPOSITO SUPIR A/N PENDI', 'modifiedby' => 'admin',]);
    }
}
