<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PenerimaanTruckingDetail;
use Illuminate\Support\Facades\DB;

class PenerimaanTruckingDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete penerimaantruckingdetail");
        DB::statement("DBCC CHECKIDENT ('penerimaantruckingdetail', RESEED, 1);");

        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '1', 'nobukti' => 'BBM 0001/II/2023', 'supir_id' => '60', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '280534', 'keterangan' => 'BBM SUPIR', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '2', 'nobukti' => 'DPO 0001/II/2023', 'supir_id' => '175', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => 'DEPOSITO', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '3', 'nobukti' => 'BBM 0002/II/2023', 'supir_id' => '175', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '418812', 'keterangan' => 'BBM', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '4', 'nobukti' => 'BBM 0003/II/2023', 'supir_id' => '83', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '270028', 'keterangan' => 'BBM', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '5', 'nobukti' => 'DPO 0002/II/2023', 'supir_id' => '94', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '6', 'nobukti' => 'BBM 0004/II/2023', 'supir_id' => '94', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '533868', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '7', 'nobukti' => 'DPO 0003/II/2023', 'supir_id' => '72', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '8', 'nobukti' => 'BBM 0005/II/2023', 'supir_id' => '72', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '311032', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '9', 'nobukti' => 'BBM 0006/II/2023', 'supir_id' => '73', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '500140', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '10', 'nobukti' => 'BBM 0007/II/2023', 'supir_id' => '267', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '545020', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '11', 'nobukti' => 'DPO 0004/II/2023', 'supir_id' => '76', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '12', 'nobukti' => 'BBM 0008/II/2023', 'supir_id' => '76', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '516596', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'PJP 0001/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => 'PJT 0018/III/2022', 'nominal' => '4166', 'keterangan' => '(LIBERTO)TAGIH SUPIR LIBERTO ATAS BIAYA TEMBUS CLOSING SHIPPER USAHA RAJIN ', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'PJP 0001/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => 'PJT 0022/VII/2022', 'nominal' => '4166', 'keterangan' => '(LIBERTO)CHARGE SUPIR LIBERTO ATAS BAN MASAK YG MELEDAK PADA GANDENGAN T-08 PANJANG DGN NO 1100 - 06301214 KETEBALAN 6MM SEBESAR RP.609.000 + RP.500.000 (BIAYA VUL 2)  TOTAL KESELURUHAN RP. 1.109.000 DENGAN PE', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'PJP 0001/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => 'PJT 0023/VII/2022', 'nominal' => '4166', 'keterangan' => '(LIBERTO)GANTI BAN DALAM KARENA BAN MELEDAK PADA GANDENGAN T-08 PANJANG SEBESAR RP.340.000 SUPIR LIBERTO', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'PJP 0001/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => 'PJT 0006/IX/2015', 'nominal' => '4170', 'keterangan' => '(LIBERTO)POTONG PINJAMAN ATAS PELUNASAN BIAYA PENYEWAAN CRANE,PERBAIKAN WARUNG & TRADO BK 8596 LU AKIBAT KECELAKAAN LIBERTO', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'PJP 0001/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => 'PJT 0014/I/2019', 'nominal' => '4166', 'keterangan' => '(LIBERTO)BIAYA PERBAIKAN 2 UNIT LOSBAK YANG DI TABRAK TRADO 8596 LU SUPIR LIBERTO (CHARGE SUPIR LIBERTO)', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '13', 'nobukti' => 'PJP 0001/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => 'PJT 0070/VIII/2019', 'nominal' => '4166', 'keterangan' => '(LIBERTO)GANTI PERBAIKAN POMPA PUM SEBESAR RP.3.565.000,-  AKIBAT KELALAIAN SUPIR LIBERTO (BK 8596 LU)', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '14', 'nobukti' => 'PJP 0002/II/2023', 'supir_id' => '0', 'pengeluarantruckingheader_nobukti' => 'PJT 0016/III/2018', 'nominal' => '20000', 'keterangan' => '(SEMUA)CHARGE BERSAMA SEMUA SUPIR ATAS LOCK GANDENGAN YANG HILANG PADA GANDENGAN T- 07 PANJANG SEBESAR RP.285.000,- DIBAGI 17 SUPIR', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '15', 'nobukti' => 'DPO 0005/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '16', 'nobukti' => 'BBM 0009/II/2023', 'supir_id' => '172', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '396032', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '17', 'nobukti' => 'DPO 0006/II/2023', 'supir_id' => '171', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '18', 'nobukti' => 'BBM 0010/II/2023', 'supir_id' => '171', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '480080', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '19', 'nobukti' => 'PJP 0003/II/2023', 'supir_id' => '298', 'pengeluarantruckingheader_nobukti' => 'PJT 0020/I/2023', 'nominal' => '400000', 'keterangan' => '(SULAIMAN)BIAYA ISI BBM TRADO TGL. 19 JANUARI 2023 UNTUK PROSES HUTANG BBM A/N SULAIMAN  ( BAYAR CASH KARENA SPBU PT. RONATAMA AGRO MIGAS  BBM KOSONG ), DIJADIKAN PJT KARENA ADA KESALAHAN TIDAK TERINPUT DI RIC 0098/I/2023', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '20', 'nobukti' => 'BBM 0011/II/2023', 'supir_id' => '298', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '530400', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '21', 'nobukti' => 'PJP 0004/II/2023', 'supir_id' => '305', 'pengeluarantruckingheader_nobukti' => 'PJT 0014/X/2022', 'nominal' => '25000', 'keterangan' => '(SYAFRIZAL)CHARGE SUPIR SYAFRIZAL ATAS BAN MASAK YG MELEDAK PANJANG DGN NO 1100  06425101 KETEBALAN 6MM SEBESAR RP.661.999 + RP.500.000 (BIAYA VUL 2)  TOTAL KESELURUHAN RP. 1.161.999 DIBULATKAN MENJADI RP.1.162', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '22', 'nobukti' => 'DPO 0007/II/2023', 'supir_id' => '305', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '23', 'nobukti' => 'BBM 0012/II/2023', 'supir_id' => '305', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '960024', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '24', 'nobukti' => 'PJP 0005/II/2023', 'supir_id' => '307', 'pengeluarantruckingheader_nobukti' => 'PJT 0002/XII/2022', 'nominal' => '12500', 'keterangan' => '(SYAIFUL BAHRI LUBIS)CHARGE SUPIR SYAIFUL ATAS BAN MASAK YG RUSAK JEBOL SAMPING PADA B 9949 JH DGN NO BAN 1100 - 06316109 KETEBALAN 4MM SEBESAR RP.420.666 + RP.500.000 (BIAYA VUL 2), TOTAL KESELURUHAN RP. 920.666 DIBULATK', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '24', 'nobukti' => 'PJP 0005/II/2023', 'supir_id' => '307', 'pengeluarantruckingheader_nobukti' => 'PJT 0062/XI/2022', 'nominal' => '12500', 'keterangan' => '(SYAIFUL BAHRI LUBIS)PINJAMAN SUPIR SYAIFUL B 9949 JH UNTUK BIAYA PERDAMAIAN, KEPOLISIAN DAN IBU SIDABUTAR ATAS LAKA DI TEBING TINGGI', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '25', 'nobukti' => 'DPO 0008/II/2023', 'supir_id' => '307', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '25000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '26', 'nobukti' => 'BBM 0013/II/2023', 'supir_id' => '307', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '405008', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '27', 'nobukti' => 'PJP 0006/II/2023', 'supir_id' => '73', 'pengeluarantruckingheader_nobukti' => 'PJT 0001/XII/2022', 'nominal' => '1250', 'keterangan' => '(DIMAS AGUNG PRABOWO)KLAIM SUPIR DIMAS AGUNG B 9120 QZ ATAS PEMBELIAN SPAREPART UNTUK SISIP MOBIL YANG KECELAKAAN  SEBESAR RP.436.000 (SPK 0002/XI/2022)', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '27', 'nobukti' => 'PJP 0006/II/2023', 'supir_id' => '73', 'pengeluarantruckingheader_nobukti' => 'PJT 0004/VIII/2022', 'nominal' => '1250', 'keterangan' => '(DIMAS AGUNG PRABOWO)CHARGE SUPIR DIMAS AGUNG ATAS BAN MASAK YG MELEDAK PADA GANDENGAN T-70 PENDEK DGN NO 1100 - 05003307 KETEBALAN 5MM SEBESAR RP.525.833 + RP.500.000 (BIAYA VUL 2)  TOTAL KESELURUHAN RP. 1.025.833 DIBULA', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '27', 'nobukti' => 'PJP 0006/II/2023', 'supir_id' => '73', 'pengeluarantruckingheader_nobukti' => 'PJT 0037/X/2022', 'nominal' => '1250', 'keterangan' => '(DIMAS AGUNG PRABOWO)PINJAMAN SUPIR DIMAS AGUNG ATAS BIAYA PERBAIKAN DI GUDANG PT. MSI KARENA NABRAK PEMBATAS ', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '27', 'nobukti' => 'PJP 0006/II/2023', 'supir_id' => '73', 'pengeluarantruckingheader_nobukti' => 'PJT 0049/XII/2022', 'nominal' => '1250', 'keterangan' => '(DIMAS AGUNG PRABOWO)KLAIM SUPIR DIMAS AGUNG ATAS LAMPU STOP YG HILANG DAN KACA SPION PETAK BESAR YG PECAH DIBUAT SUPIR SEBESAR RP.162.000 (SPK 0087/XII/2022)', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '28', 'nobukti' => 'DPO 0009/II/2023', 'supir_id' => '73', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '5000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '29', 'nobukti' => 'PJP 0007/II/2023', 'supir_id' => '146', 'pengeluarantruckingheader_nobukti' => 'PJT 0021/XII/2022', 'nominal' => '50000', 'keterangan' => '(JANTO)CHARGE SUPIR JANTO ATAS BAN MASAK YG RUSAK/LEPAS BUNGA PADA B 9508 PH DGN NO BAN 1100  06415111 KETEBALAN 5MM SEBESAR RP.525.833 + RP.500.000 (BIAYA VUL 2), TOTAL KESELURUHAN RP. 1.025.833 DIBULATKAN', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '30', 'nobukti' => 'DPO 0010/II/2023', 'supir_id' => '146', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '50000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '31', 'nobukti' => 'BBM 0014/II/2023', 'supir_id' => '146', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '760104', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '32', 'nobukti' => 'PJP 0008/II/2023', 'supir_id' => '0', 'pengeluarantruckingheader_nobukti' => 'PJT 0016/III/2018', 'nominal' => '20000', 'keterangan' => '(SEMUA)CHARGE BERSAMA SEMUA SUPIR ATAS LOCK GANDENGAN YANG HILANG PADA GANDENGAN T- 07 PANJANG SEBESAR RP.285.000,- DIBAGI 17 SUPIR', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '33', 'nobukti' => 'DPO 0011/II/2023', 'supir_id' => '311', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '75000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '34', 'nobukti' => 'BBM 0015/II/2023', 'supir_id' => '311', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '620024', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
        penerimaantruckingdetail::create(['penerimaantruckingheader_id' => '35', 'nobukti' => 'DPO 0012/II/2023', 'supir_id' => '72', 'pengeluarantruckingheader_nobukti' => '', 'nominal' => '5000', 'keterangan' => '', 'modifiedby' => 'ADMIN',]);
    }
}
