<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PenerimaanHeader;
use Illuminate\Support\Facades\DB;

class PenerimaanHeaderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete penerimaanheader");
        DB::statement("DBCC CHECKIDENT ('penerimaanheader', RESEED, 1);");


        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0001/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'KANTOR PUSAT', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0002/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '63', 'bank_id' => '4', 'postingdari' => 'ENTRY PELUNASAN PIUTANG', 'diterimadari' => 'TAS AHAI', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0003/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '64', 'bank_id' => '4', 'postingdari' => 'ENTRY PELUNASAN PIUTANG', 'diterimadari' => 'TAS AP', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0004/II/2023', 'tglbukti' => '2023/2/7', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'CABANG SURABAYA', 'tgllunas' => '2023/2/7', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0005/II/2023', 'tglbukti' => '2023/2/7', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'CABANG SURABAYA', 'tgllunas' => '2023/2/7', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0006/II/2023', 'tglbukti' => '2023/2/7', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'CABANG SURABAYA', 'tgllunas' => '2023/2/7', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0007/II/2023', 'tglbukti' => '2023/2/7', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'CABANG MAKASSAR', 'tgllunas' => '2023/2/7', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0008/II/2023', 'tglbukti' => '2023/2/8', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'KANTOR PUSAT', 'tgllunas' => '2023/2/8', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0009/II/2023', 'tglbukti' => '2023/2/8', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'CABANG SURABAYA', 'tgllunas' => '2023/2/8', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0010/II/2023', 'tglbukti' => '2023/2/9', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '64', 'bank_id' => '4', 'postingdari' => 'ENTRY PELUNASAN PIUTANG', 'diterimadari' => 'TAS AP', 'tgllunas' => '2023/2/9', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0011/II/2023', 'tglbukti' => '2023/2/10', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'BANK BCA', 'tgllunas' => '2023/2/10', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0012/II/2023', 'tglbukti' => '2023/2/15', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'KANTOR PUSAT', 'tgllunas' => '2023/2/15', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0013/II/2023', 'tglbukti' => '2023/2/16', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '64', 'bank_id' => '4', 'postingdari' => 'ENTRY PELUNASAN PIUTANG', 'diterimadari' => 'TAS AP', 'tgllunas' => '2023/2/16', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0014/II/2023', 'tglbukti' => '2023/2/17', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'KANTOR PUSAT', 'tgllunas' => '2023/2/17', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0015/II/2023', 'tglbukti' => '2023/2/22', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'KANTOR PUSAT', 'tgllunas' => '2023/2/22', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0016/II/2023', 'tglbukti' => '2023/2/23', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '64', 'bank_id' => '4', 'postingdari' => 'ENTRY PELUNASAN PIUTANG', 'diterimadari' => 'TAS AP', 'tgllunas' => '2023/2/23', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'BMT-M BCA3 0017/II/2023', 'tglbukti' => '2023/2/24', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '4', 'postingdari' => 'ENTRY PENERIMAAN KAS/BANK', 'diterimadari' => 'KANTOR PUSAT', 'tgllunas' => '2023/2/24', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '268', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'KMT 0001/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '1', 'postingdari' => 'PROSES GAJI SUPIR', 'diterimadari' => 'PROSES GAJI SUPIR PERIODE 01-02-2023 S/D 01-02-2023', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '32', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'KMT 0002/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '1', 'postingdari' => 'PROSES GAJI SUPIR', 'diterimadari' => 'PROSES GAJI SUPIR PERIODE 01-02-2023 S/D 01-02-2023', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '32', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'KMT 0003/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '1', 'postingdari' => 'PROSES GAJI SUPIR', 'diterimadari' => 'PROSES GAJI SUPIR PERIODE 01-02-2023 S/D 01-02-2023', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '32', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
        penerimaanheader::create(['nobukti' => 'KMT 0004/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'agen_id' => '0', 'bank_id' => '1', 'postingdari' => 'PROSES GAJI SUPIR', 'diterimadari' => 'PROSES GAJI SUPIR PERIODE 01-02-2023 S/D 01-02-2023', 'tgllunas' => '2023/2/1', 'statusapproval' => '4', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statusberkas' => '0', 'userberkas' => '', 'tglberkas' => '1900/1/1', 'statusformat' => '32', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'modifiedby' => 'ADMIN',]);
    }
}
