<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PengeluaranTruckingDetail;
use Illuminate\Support\Facades\DB;

class PengeluaranTruckingDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("delete pengeluarantruckingdetail");
        DB::statement("DBCC CHECKIDENT ('pengeluarantruckingdetail', RESEED, 1);");

        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '1', 'nobukti' => 'PJT 0025/III/2023', 'karyawan_id' => '0', 'supir_id' => '7', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '70000.00', 'keterangan' => '(ADERIAN VALENTIN YUSUF)Pinjaman Supir Aderian BK 9690 XA untuk Biaya Denda karena merokok di Gudang Charoen Phokphand Tgl. 24 Maret 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '2', 'nobukti' => 'PJT 0005/II/2023', 'karyawan_id' => '0', 'supir_id' => '10', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '150000.00', 'keterangan' => '(ADY GUNAWAN)Pinjaman Supir Ady Gunawan BK 8747 BU atas Biaya putra pintu container full Asahimas yang salah posisi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '3', 'nobukti' => 'PJT 0008/II/2023', 'karyawan_id' => '0', 'supir_id' => '10', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '451912.00', 'keterangan' => '(ADY GUNAWAN)Gaji Minus Supir Ady Gunawan BK 8747 BU Tgl. 08 Februari 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '4', 'nobukti' => 'PJT 0023/II/2023', 'karyawan_id' => '0', 'supir_id' => '50', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '319922.00', 'keterangan' => '(BAYU PAMUNGKAS)Gaji Minus Supir Bayu BK 8747 BU Tgl. 22 Februari 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '5', 'nobukti' => 'PJT 0030/III/2023', 'karyawan_id' => '0', 'supir_id' => '158', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '75000.00', 'keterangan' => '(JANTO)Pinjaman Supir Janto B 9508 PH atas Biaya Pindah kapal Shipper Avi Farma sebesar Rp. 112.500', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '6', 'nobukti' => 'PJT 0024/III/2023', 'karyawan_id' => '0', 'supir_id' => '172', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '5100.00', 'keterangan' => '(JULIADI MANURUNG)Pinjaman Supir Juliadi BK 9418 LO untuk Biaya gantii seal yang salah pasang di MSI sebesar Rp. 76.500', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '7', 'nobukti' => 'PJT 0034/IV/2023', 'karyawan_id' => '0', 'supir_id' => '172', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '69318.00', 'keterangan' => '(JULIADI MANURUNG)Gaji Minus Supir Juliadi Manurung BK 9418 LO Tgl. 28 April 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '8', 'nobukti' => 'PJT 0018/III/2022', 'karyawan_id' => '0', 'supir_id' => '184', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '358647.00', 'keterangan' => '(Liberto)Tagih Supir Liberto atas Biaya Tembus Closing shipper Usaha Rajin ', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '9', 'nobukti' => 'PJT 0008/I/2023', 'karyawan_id' => '0', 'supir_id' => '260', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '600304.00', 'keterangan' => '(RAMADANI GINTING)Pinjaman Supir Ramadani atas Biaya Isi BBM Trado Tgl. 10 Januari 2023 untuk proses Hutang BBM yang belakangan diisi untuk Tgl. 23 Desember 2022 RIC 0133/XII/2022', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '10', 'nobukti' => 'PJT 0040/XII/2022', 'karyawan_id' => '0', 'supir_id' => '260', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '1087587.00', 'keterangan' => '(RAMADANI GINTING)Gaji Minus Supir Ramadani BK 8747 BU Tgl. 21 Desember 2022', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '11', 'nobukti' => 'PJT 0009/IV/2023', 'karyawan_id' => '0', 'supir_id' => '273', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '3681.00', 'keterangan' => '(RIZKY ARFANSYAH)Biaya Isi BBM Trando BK 8741 BU Spir Rizky yang terakhir diisi ( Supir sudah tidak masuk kerja lagi )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '12', 'nobukti' => 'PJT 0033/IV/2023', 'karyawan_id' => '0', 'supir_id' => '317', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '36419.00', 'keterangan' => '(SULAIMAN)Gaji Minus Supir Sulaiman B 9668 QZ Tgl. 28 April 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '13', 'nobukti' => 'PJT 0018/IV/2023', 'karyawan_id' => '1', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '1522000.00', 'keterangan' => '(DONAL T SINAGA)Pinjaman Mandor Donal untuk Biaya Tembus closing No. Container MRTU 2258798 & MRTU 2203774 sebesar Rp. 1.722.000 ( Dipotong dari Gaji Rp. 200.000 / Bln, Mulai bulan April 2023 )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '14', 'nobukti' => 'PJT 0025/II/2023', 'karyawan_id' => '2', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '485000.00', 'keterangan' => '(JOKO SUKIRNO)Pinjaman Mekanik Joko Sukirno atas Biaya bayar tunggakan BPJS sebesar Rp. 3.482.500 + Rp. 2.500 Biaya adm ( Dipotong dari Gaji Rp. 1.000.000 / Bulan, Mulai Bulan Februari 2023 )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '15', 'nobukti' => 'PJT 0039/VIII/2022', 'karyawan_id' => '3', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '10611000.00', 'keterangan' => '(NG BIN SAN)Pinjaman Bp. Asan untuk Biaya Demurage Periode Desember 2021 - 05 Juli 2022 sebesar Rp. 11.611.000 ( Dipotong dari fee Rp. 1.000.000 / Bln, Dimulai sesudah Pinjaman yng lama habis dipotong )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '16', 'nobukti' => 'PJT 0043/VI/2022', 'karyawan_id' => '3', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '10910000.00', 'keterangan' => '(NG BIN SAN)Pinjaman Bp. Asan untuk Biaya Demurage Periode Desember 2021 - 31 Mei 2022 sebesar Rp. 19.910.000 ( Dipotong dari fee Rp. 1.000.000 / Bln, Mulai Bln Juni 2022 )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '17', 'nobukti' => 'PJT 0001/IV/2023', 'karyawan_id' => '0', 'supir_id' => '64', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '4695000.00', 'keterangan' => '(CHANDRA ARIANTO TAMPUBOLON)Pinjaman Supir Chandra BK 8743 BU atas Biaya Ganti rugi / damai Trado BK 8743 BU Supir Cahandra yang nabrak orang di Depo PJN Tgl. 20 Maret 2023 sebesar Rp. 5.000.000 ( Ada klaim asuransi )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '18', 'nobukti' => 'PJT 0004/III/2023', 'karyawan_id' => '0', 'supir_id' => '158', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '245000.00', 'keterangan' => '(JANTO)Pinjaman Supir Janto B 9508 PH untuk Biaya perbaikan tembok Indo Maraet Tamora yang ditabrak sebesar Rp. 335.000', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '19', 'nobukti' => 'PJT 0021/XII/2022', 'karyawan_id' => '0', 'supir_id' => '158', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '345800.00', 'keterangan' => '(JANTO)Charge supir Janto atas Ban Masak yg Rusak/Lepas Bunga pada B 9508 PH dgn no ban 1100 - 06415111 ketebalan 5mm sebesar Rp.525.833 + Rp.500.000 (Biaya Vul 2), total keseluruhan Rp. 1.025.833 Dibulatkan', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '20', 'nobukti' => 'PJT 0036/III/2023', 'karyawan_id' => '0', 'supir_id' => '158', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '8712500.00', 'keterangan' => '(JANTO)Pinjaman Supir Janto B 9508PH untuk Biaya Ganti rugi perbaikan di Bengkel Unity Automobile atas Mobil Honda CRV BK 1450 CY yang ditabrak oleh Supir Janto ( Ada Klaim Asuransi )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '21', 'nobukti' => 'PJT 0016/II/2023', 'karyawan_id' => '0', 'supir_id' => '161', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '184000.00', 'keterangan' => '(JOHANNES SIMANGUNSONG)CHARGE SUPIR JOHANNES SIMANGUNSONG YG MEMBUAT AKI PECAH PADA BK 9451 LO SEBESAR RP.184,109. SISA AKI  96 HARI, DGN PERHITUNGAN : (HARGA HARGA BARU AKI Rp.1.400.000 : 730 HARI x SISA PEMAKAIAN, (HARGA ', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '22', 'nobukti' => 'PJT 0017/II/2023', 'karyawan_id' => '0', 'supir_id' => '161', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '184000.00', 'keterangan' => '(JOHANNES SIMANGUNSONG)CHARGE SUPIR JOHANNES SIMANGUNSONG YG MEMBUAT AKI PECAH PADA BK 9451 LO SEBESAR RP.184,109. SISA AKI  96 HARI, DGN PERHITUNGAN : (HARGA HARGA BARU AKI Rp.1.400.000 : 730 HARI x SISA PEMAKAIAN, (HARGA ', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '23', 'nobukti' => 'PJT 0015/III/2023', 'karyawan_id' => '0', 'supir_id' => '172', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '516200.00', 'keterangan' => '(JULIADI MANURUNG)Biaya Perbaikan Atap yang ditabarak Supir Juliadi BK 9418 LO di PT. AKS Tgl. 04 Maret 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '24', 'nobukti' => 'PJT 0037/III/2023', 'karyawan_id' => '0', 'supir_id' => '172', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '4066200.00', 'keterangan' => '(JULIADI MANURUNG)KLAIM SUPIR JULIADI MANURUNG ATAS 1 SET KAKI GANDENGAN YG RUDAK DIBUAT SUPIR SEBESAR RP.4.100.000 PADA GANDENGAN T-59 PENDEK', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '25', 'nobukti' => 'PJT 0006/IX/2015', 'karyawan_id' => '0', 'supir_id' => '184', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '9053439.00', 'keterangan' => '(Liberto)Potong Pinjaman atas Pelunasan biaya penyewaan crane,perbaikan warung & Trado BK 8596 LU akibat kecelakaan Liberto', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '26', 'nobukti' => 'PJT 0022/VII/2022', 'karyawan_id' => '0', 'supir_id' => '184', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '719147.00', 'keterangan' => '(Liberto)Charge supir Liberto atas Ban Masak yg Meledak pada Gandengan T-08 Panjang dgn no 1100 - 06301214 ketebalan 6mm sebesar Rp.609.000 + Rp.500.000 (Biaya Vul 2)  total keseluruhan Rp. 1.109.000 dengan pe', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '27', 'nobukti' => 'PJT 0070/VIII/2019', 'karyawan_id' => '0', 'supir_id' => '184', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '1718526.00', 'keterangan' => '(Liberto)GANTI PERBAIKAN POMPA PUM SEBESAR Rp.3.565.000,-  AKIBAT KELALAIAN SUPIR LIBERTO (BK 8596 LU)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '28', 'nobukti' => 'PJT 0005/IV/2023', 'karyawan_id' => '0', 'supir_id' => '196', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '1357500.00', 'keterangan' => '(M. YUSUF)GANTI 1 BUAH AKI YANG HILANG DIAMBIL LAWA-LAWA DI JALAN, DGN NO AKI CCB041748E-2 (SISA 688 HARI). CHARGE SUPIR M.YUSUF BK 8208 BQ SEBESAR RP.1.432.547 (HARGA DIBULATKAN MENJADI RP.1.432.500).(PERHITUN', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '29', 'nobukti' => 'PJT 0023/IV/2023', 'karyawan_id' => '0', 'supir_id' => '196', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '450000.00', 'keterangan' => '(M. YUSUF)Pinjaman Supir M. Yusuf BK 8208 BQ atas biaya ganti rugi nabrak pot bunga dan beton saluran air yang pecah di Indocafe Tamora sebesar Rp. 500.000 Tgl. 13 April 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '30', 'nobukti' => 'PJT 0035/IV/2023', 'karyawan_id' => '0', 'supir_id' => '196', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '85000.00', 'keterangan' => '(M. YUSUF)GANTI 1 DIRIGEN AIR KERAS UNTUK BATERAI YG HILANG DIAMBIL LAWA-LAWA, CHARGE SUPIR M. YUSUF BK 8208 BQ SEBESAR RP.85.0000', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '31', 'nobukti' => 'PJT 0036/IV/2023', 'karyawan_id' => '0', 'supir_id' => '196', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '50000.00', 'keterangan' => '(M. YUSUF)GANTI 2 SET KEPALA BATERAI YG HILANG DIAMBIL LAWA-LAWA, CHARGE SUPIR M. YUSUF BK 8208 BQ SEBESAR RP.50.000 (SPK 0037/IV/2023)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '32', 'nobukti' => 'PJT 0036/XII/2022', 'karyawan_id' => '0', 'supir_id' => '260', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '244484.00', 'keterangan' => '(RAMADANI GINTING)KLAIM SUPIR RAMADANI GINTING ATAS KACA KABIN BELAKANG YG PECAH DIBUAT SUPIR SEBESAR RP.250.000 (SPK 0071/XII/2022)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '33', 'nobukti' => 'PJT 0044/XI/2022', 'karyawan_id' => '0', 'supir_id' => '285', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '14192369.00', 'keterangan' => '(SAHBUDIN)Setor ke Pancaran Jatinusa atas Biaya Repairing Container CAIU 4636498, TXGU 5303991 yang jatuh ditabrak oleh Supir Sahbudin sebesar Rp. 16.642.369,- ( Dijadikan PJT Supir )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '34', 'nobukti' => 'PJT 0001/VI/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '663922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-16 Panjang dgn no ban 1100 - 01020101 sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '35', 'nobukti' => 'PJT 0001/VIII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '463922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 2016207 pada Gandengan T-34 Panjang sebesar Rp.500.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '36', 'nobukti' => 'PJT 0001/XI/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '490000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-28 Pendek dgn no ban 1100 - 02118214 sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '37', 'nobukti' => 'PJT 0003/II/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '460000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-22 Panjang  sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '38', 'nobukti' => 'PJT 0003/VII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '783922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-36 Panjang dgn no ban 1100 - 0910105 sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '39', 'nobukti' => 'PJT 0004/III/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '225000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-33 Panjang  sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '40', 'nobukti' => 'PJT 0005/IV/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '228922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 21 Panjang sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '41', 'nobukti' => 'PJT 0005/X/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '265000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-08 Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '42', 'nobukti' => 'PJT 0006/III/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '725000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-17 Panjang  sebesar Rp.805.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '43', 'nobukti' => 'PJT 0007/X/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '265000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-67 Pendek sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '44', 'nobukti' => 'PJT 0008/VI/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '783922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-45 Panjang dgn no ban 1100 - 1908205 sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '45', 'nobukti' => 'PJT 0009/III/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '225000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-14 Panjang  sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '46', 'nobukti' => 'PJT 0009/VII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '258922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-27 Panjang sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '47', 'nobukti' => 'PJT 0010/IV/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '158922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 62Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '48', 'nobukti' => 'PJT 0010/VII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '158922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-46 Panjang sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '49', 'nobukti' => 'PJT 0011/VII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '258922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-46 Panjang sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '50', 'nobukti' => 'PJT 0013/X/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '590000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang lepas bunga pada Gandengan T-19 Panjang dgn no ban 1100 - 06309303 sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '51', 'nobukti' => 'PJT 0015/III/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '105000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-62 Panjang  sebesar Rp.285.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '52', 'nobukti' => 'PJT 0015/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '583922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak dengan no ban 1100 - 0803214-1 pada Gandengan T-51 Panjang sebesar Rp.600.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '53', 'nobukti' => 'PJT 0015/V/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '238922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 24 Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '54', 'nobukti' => 'PJT 0016/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '500000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak pada Gandengan T-46 Panjang dgn no ban 1100 - 0210312  sebesar Rp.600.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '55', 'nobukti' => 'PJT 0016/VIII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '383922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak/lepas bunga dgn no ban 1100 - 0829209 pada Gandengan T-48 Pendek sebesar Rp.400.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '56', 'nobukti' => 'PJT 0019/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '210000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-35 Panjang  sebesar Rp.270.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '57', 'nobukti' => 'PJT 0020/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '740000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 06523105  pada Gandengan T-01 Panjang  sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '58', 'nobukti' => 'PJT 0020/XII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '490000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-64 Pendek dgn no ban 1100 - 02118305 sebesar Rp.500.000,- dibagi 15 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '59', 'nobukti' => 'PJT 0021/XII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '590000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-05 Panjang dgn no ban 1100 - 1008313 sebesar Rp.600.000,- dibagi 15 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '60', 'nobukti' => 'PJT 0022/IV/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '663922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T- 13 Panjang dgn no ban 1100 - 2008207 setebal 7mm sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '61', 'nobukti' => 'PJT 0023/VII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '683922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 0818307 pada Gandengan T-46 Panjang sebesar Rp.700.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '62', 'nobukti' => 'PJT 0026/I/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '345000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas ban yang meledak pada Gandengan T-64 Pendek  sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '63', 'nobukti' => 'PJT 0026/IV/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '383922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Rusak/Koyak Besar pada Gandengan T- 51 Panjang dgn no ban 1100 - 0925207 setebal 4mm sebesar Rp.400.000,- dibagi 19 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '64', 'nobukti' => 'PJT 0027/I/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '235000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-43 Panjang  sebesar Rp.275.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '65', 'nobukti' => 'PJT 0028/II/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '360000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-45 Panjang  sebesar Rp.400.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '66', 'nobukti' => 'PJT 0028/III/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '210198.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 2003303 pada Gandengan T- 01 Panjang sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '67', 'nobukti' => 'PJT 0028/IV/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '783922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T- 45 Panjang dgn no ban 1100 - 2008114 setebal 8mm sebesar Rp.800.000,- dibagi 19 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '68', 'nobukti' => 'PJT 0029/IV/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '783922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Rusak/Lepas Bunga pada Gandengan T- 45 Panjang dgn no ban 1100 - 1908208 setebal 8mm sebesar Rp.800.000,- dibagi 19 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '69', 'nobukti' => 'PJT 0030/I/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '1080000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas ban yang meledak pada Gandengan T-30 Panjang  sebesar Rp.1.100.000,- dibagi 16 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '70', 'nobukti' => 'PJT 0030/III/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '763922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1019202 pada Gandengan T- 53 Panjang sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '71', 'nobukti' => 'PJT 0032/VII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '783922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 06321311 pada Gandengan T-18 Panjang sebesar Rp.800.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '72', 'nobukti' => 'PJT 0033/III/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '463922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1017209 pada Gandengan T- 60 Pendek sebesar Rp.500.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '73', 'nobukti' => 'PJT 0034/VIII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '258922.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-44 Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '74', 'nobukti' => 'PJT 0034/XII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '275000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-03 Panjang  sebesar Rp.275.000,- dibagi 15 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '75', 'nobukti' => 'PJT 0035/I/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '255000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-37 Panjang  sebesar Rp.275.000,- dibagi 16 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '76', 'nobukti' => 'PJT 0036/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '790000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dengan no ban 1100 - 04923201 pada Gandengan T-39 Panjang sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '77', 'nobukti' => 'PJT 0037/III/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '320000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang afkir dgn no ban 1100-0804106  pada Gandengan T-57 PENDEK  sebesar Rp.400.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '78', 'nobukti' => 'PJT 0037/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '590000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dengan no ban 1100 - 02105301 pada Gandengan T-23 Panjang sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '79', 'nobukti' => 'PJT 0038/XII/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '400000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-25 Panjang dgn no ban 1100 - 2015206  sebesar Rp.400.000,- dibagi 15 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '80', 'nobukti' => 'PJT 0046/III/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '205000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-33 Panjang  sebesar Rp.285.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '81', 'nobukti' => 'PJT 0047/XI/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '290000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-30 Panjang dgn no ban 1100 - 0820110-2 sebesar Rp.300.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '82', 'nobukti' => 'PJT 0048/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '590000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang RUSAK dengan no ban 1100 - 1906303 pada Gandengan T-07 Panjang sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '83', 'nobukti' => 'PJT 0048/XI/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '490000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-51 Panjang dgn no ban 1100 - 04918304 sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '84', 'nobukti' => 'PJT 0049/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '690000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04918306 yang hilang pada Gandengan T-32 Panjang sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '85', 'nobukti' => 'PJT 0050/II/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '380000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-72 Panjang  sebesar Rp.400.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '86', 'nobukti' => 'PJT 0052/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '508452.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1013305  pada Gandengan T-16 Panjang setebal 6mm sebesar Rp.600.000,- dibagi 18 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '87', 'nobukti' => 'PJT 0054/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '690000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1013312 yang hilang pada Gandengan T-08 Panjang sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '88', 'nobukti' => 'PJT 0055/IX/2018', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '790000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 0210311 yang hilang pada Gandengan T-62 Panjang sebesar Rp.800.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '89', 'nobukti' => 'PJT 0057/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '735000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04922301  pada Gandengan T-31 Panjang setebal 8mm sebesar Rp.800.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '90', 'nobukti' => 'PJT 0066/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '660000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 01028301 pada Gandengan T-16 Panjang setebal 7mm sebesar Rp.700.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '91', 'nobukti' => 'PJT 0080/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '720000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04918310  pada Gandengan T-18 Panjang setebal 8mm sebesar Rp.800.000,- dibagi 18 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '92', 'nobukti' => 'PJT 0081/IV/2019', 'karyawan_id' => '0', 'supir_id' => '0', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '740000.00', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 06315116  pada Gandengan T-62 Panjang setebal 8mm sebesar Rp.800.000,- dibagi 18 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '93', 'nobukti' => 'PJT 0029/IV/2023', 'karyawan_id' => '0', 'supir_id' => '317', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '52000.00', 'keterangan' => '(SULAIMAN)KLAIM SUPIR SULAIMAN ATAS KACA SPION PETAK BESAR YG PECAH DIBUAT SUPIR SEBESAR RP.52.000 (SPK 0077/IV/2023)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '94', 'nobukti' => 'PJT 0014/X/2022', 'karyawan_id' => '0', 'supir_id' => '325', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '184500.00', 'keterangan' => '(SYAFRIZAL)Charge supir Syafrizal atas Ban Masak yg meledak Panjang dgn no 1100 - 06425101 ketebalan 6mm sebesar Rp.661.999 + Rp.500.000 (Biaya Vul 2)  total keseluruhan Rp. 1.161.999 Dibulatkan menjadi Rp.1.162', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '95', 'nobukti' => 'PJT 0022/III/2023', 'karyawan_id' => '0', 'supir_id' => '325', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '4162500.00', 'keterangan' => '(SYAFRIZAL)Biaya Ganti rugi / damai, dll Gerobak B 9807 ZI yang lepas velg sebelah kiri dan terlempar sehingga mengenai sterling, pintu rumah dan sepeda motor BK 6741 ADL Rp. 8.560.000 ( dibagi 2 TAS dan Supir )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '96', 'nobukti' => 'PJT 0002/XII/2022', 'karyawan_id' => '0', 'supir_id' => '327', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '275700.00', 'keterangan' => '(SYAIFUL BAHRI LUBIS)Charge supir Syaiful atas Ban Masak yg Rusak Jebol Samping pada B 9949 JH dgn no ban 1100 - 06316109 ketebalan 4mm sebesar Rp.420.666 + Rp.500.000 (Biaya Vul 2), total keseluruhan Rp. 920.666 Dibulatk', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '97', 'nobukti' => 'PJT 0062/XI/2022', 'karyawan_id' => '0', 'supir_id' => '327', 'trado_id' => '0', 'stok_id' => '0', 'pengeluaranstok_nobukti' => '', 'qty' => '0.00', 'harga' => '0.00', 'total' => '0.00', 'penerimaantruckingheader_nobukti' => '', 'invoice_nobukti' => '', 'orderantrucking_nobukti' => '', 'nominal' => '6042500.00', 'keterangan' => '(SYAIFUL BAHRI LUBIS)Pinjaman Supir Syaiful B 9949 JH untuk Biaya Perdamaian, Kepolisian dan Ibu Sidabutar atas Laka di Tebing Tinggi', 'modifiedby' => 'RYAN',]);
    }
}
