<?php

namespace Database\Seeders;

use App\Models\PengeluaranHeader;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PengeluaranHeaderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::statement("delete pengeluaranheader");
        DB::statement("DBCC CHECKIDENT ('pengeluaranheader', RESEED, 1);");


        pengeluaranheader::create(['nobukti' => 'KBT 0001/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '0', 'postingdari' => 'ENTRY PENGELUARAN TRUCKING', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0002/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '0', 'postingdari' => 'ENTRY PENGELUARAN TRUCKING', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0003/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '0', 'postingdari' => 'ENTRY PENGELUARAN TRUCKING', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0004/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '0', 'postingdari' => 'ENTRY PENGELUARAN TRUCKING', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0006/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY PENGELUARAN KAS/BANK', 'statusapproval' => '4', 'dibayarke' => 'SUPIR', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0007/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => 'SETOR FEE HARRY ANANDA ATAS RITASI UNIT TRADO YANG JALAN BULAN JANUARI 2023 = 302 UNIT @ RP. 2.500', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => '', 'statusapproval' => '4', 'dibayarke' => 'MEKANIK PARDEDE', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0008/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => 'BIAYA JASA PENGAMANAN TRADO DI BELAWAN MAR 84 BULAN FEBRUARI 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => '', 'statusapproval' => '4', 'dibayarke' => 'IBU SUTOMO', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0005/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '0', 'postingdari' => 'ENTRY PROSES GAJI SUPIR', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0011/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY PENGELUARAN KAS/BANK', 'statusapproval' => '4', 'dibayarke' => 'KERNEK', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0012/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => 'Biaya Sewa Kost untuk Mekanik Jakarta yang dinas di Medan a/n Abdul Manan Sutisna bulan Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => '', 'statusapproval' => '4', 'dibayarke' => 'MEKANIK JAKARTA', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0013/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => 'Biaya Isi BBM Trado Tgl. 30 & 31 Januari 2022 untuk proses Hutang BBM', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY PENGELUARAN KAS/BANK', 'statusapproval' => '4', 'dibayarke' => 'PT. RONATAMA AGRO MIGAS', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0014/II/2023', 'tglbukti' => '2023/2/1', 'keterangan' => 'Lebih bayar Gaji Supir Erikson BK 8264 FB di RIC 0003/II/2022 sebesar Rp. 52.200', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY PENGELUARAN KAS/BANK', 'statusapproval' => '4', 'dibayarke' => 'SUPIR', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0025/II/2023', 'tglbukti' => '2023/2/2', 'keterangan' => '', 'pelanggan_id' => '0', 'alatbayar_id' => '0', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'ADMIN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0026/II/2023', 'tglbukti' => '2023/2/2', 'keterangan' => '(KGT 0006/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 03 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0034/II/2023', 'tglbukti' => '2023/2/3', 'keterangan' => '(KGT 0008/II/2023) Kas Gantung Pak Harry untuk buat kunci BK 8007 XA ( yang lama aus atau patah )', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0035/II/2023', 'tglbukti' => '2023/2/3', 'keterangan' => '(KGT 0009/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 04 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0036/II/2023', 'tglbukti' => '2023/2/3', 'keterangan' => '(KGT 0010/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 06 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0055/II/2023', 'tglbukti' => '2023/2/6', 'keterangan' => '(KGT 0014/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 07 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0064/II/2023', 'tglbukti' => '2023/2/7', 'keterangan' => '(KGT 0015/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 08 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0063/II/2023', 'tglbukti' => '2023/2/7', 'keterangan' => '(KGT 0017/II/2023) Kas Gantung Meknaik Sukirno untuk beli dempul & baut ', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0074/II/2023', 'tglbukti' => '2023/2/8', 'keterangan' => '(KGT 0019/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 09 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0077/II/2023', 'tglbukti' => '2023/2/9', 'keterangan' => '(KGT 0020/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 10 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0093/II/2023', 'tglbukti' => '2023/2/10', 'keterangan' => '(KGT 0023/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 11 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0094/II/2023', 'tglbukti' => '2023/2/10', 'keterangan' => '(KGT 0024/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 13 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0108/II/2023', 'tglbukti' => '2023/2/13', 'keterangan' => '(KGT 0026/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 14 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0116/II/2023', 'tglbukti' => '2023/2/14', 'keterangan' => '(KGT 0027/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 15 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0125/II/2023', 'tglbukti' => '2023/2/15', 'keterangan' => '(KGT 0030/II/2023) Kas Gantung Supir Dedi untuk antar Mekanik Budiman ke Bandara ( untuk standby biaya jika bagasi melebihi bobot )', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0126/II/2023', 'tglbukti' => '2023/2/15', 'keterangan' => '(KGT 0031/II/2023) Kas Gantung Ko Asan untuk Biaya Vaksin Covid Boster Mekanik Budiman', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0127/II/2023', 'tglbukti' => '2023/2/15', 'keterangan' => '(KGT 0032/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 16 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0138/II/2023', 'tglbukti' => '2023/2/16', 'keterangan' => '(KGT 0035/II/2023) Kas Gantung Mekanik Sukirno untuk ambil perbaikan Dexel', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0139/II/2023', 'tglbukti' => '2023/2/16', 'keterangan' => '(KGT 0036/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 17 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0148/II/2023', 'tglbukti' => '2023/2/17', 'keterangan' => '(KGT 0037/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 20 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0161/II/2023', 'tglbukti' => '2023/2/20', 'keterangan' => '(KGT 0041/II/2023) Kas Gantung Ko Asan untuk beli keperluan sembahyang', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0162/II/2023', 'tglbukti' => '2023/2/20', 'keterangan' => '(KGT 0042/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 21 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0170/II/2023', 'tglbukti' => '2023/2/21', 'keterangan' => '(KGT 0043/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 22 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0184/II/2023', 'tglbukti' => '2023/2/22', 'keterangan' => '(KGT 0044/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 22 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0185/II/2023', 'tglbukti' => '2023/2/22', 'keterangan' => '(KGT 0045/II/2023) Kas Gantung Mekanik Manik untuk isi minyak ', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0193/II/2023', 'tglbukti' => '2023/2/23', 'keterangan' => '(KGT 0047/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 24 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0207/II/2023', 'tglbukti' => '2023/2/24', 'keterangan' => '(KGT 0051/II/2023) Kas Gantung Ko Asan untuk service Mobil Avanza BK 1285 HN', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0208/II/2023', 'tglbukti' => '2023/2/24', 'keterangan' => '(KGT 0052/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 25 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0209/II/2023', 'tglbukti' => '2023/2/24', 'keterangan' => '(KGT 0053/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 27 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0225/II/2023', 'tglbukti' => '2023/2/27', 'keterangan' => '(KGT 0055/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 28 Februari 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0237/II/2023', 'tglbukti' => '2023/2/28', 'keterangan' => '(KGT 0057/II/2023) Kas Gantung Ko Asan untuk Beli kebutuhan kantor', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
        pengeluaranheader::create(['nobukti' => 'KBT 0238/II/2023', 'tglbukti' => '2023/2/28', 'keterangan' => '(KGT 0058/II/2023) Kas Gantung untuk Uang Jalan Supir Tgl. 01 Maret 2023', 'pelanggan_id' => '0', 'alatbayar_id' => '1', 'postingdari' => 'ENTRY KAS GANTUNG', 'statusapproval' => '4', 'dibayarke' => '', 'bank_id' => '1', 'userapproval' => '', 'tglapproval' => '1900/1/1', 'statuscetak' => '175', 'userbukacetak' => '', 'tglbukacetak' => '1900/1/1', 'jumlahcetak' => '0', 'transferkeac' => '', 'transferkean' => '', 'transferkebank' => '', 'statusformat' => '33', 'modifiedby' => 'AYEN',]);
    }
}
