<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PengeluaranTruckingDetail;
use Illuminate\Support\Facades\DB;

class PengeluaranTruckingDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("delete pengeluarantruckingdetail");
        DB::statement("DBCC CHECKIDENT ('pengeluarantruckingdetail', RESEED, 1);");

        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '1', 'nobukti' => 'PJT 0001/II/2023', 'supir_id' => '60', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '19645', 'keterangan' => 'GAJI MINUS SUPIR CHANDRA BK 8743 BU TGL. 01 FEBRUARI 2023', 'modifiedby' => 'ADMIN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '2', 'nobukti' => 'PJT 0002/II/2023', 'supir_id' => '83', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '100780', 'keterangan' => 'GAJI MINUS SUPIR ERIKSON BK 8264 FB TGL. 01 FEBRUARI 2023', 'modifiedby' => 'ADMIN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '3', 'nobukti' => 'PJT 0003/II/2023', 'supir_id' => '267', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '33408', 'keterangan' => 'GAJI MINUS SUPIR SAHBUDIN  BK 8178 EW TGL. 01 FEBRUARI 2023', 'modifiedby' => 'ADMIN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '4', 'nobukti' => 'PJT 0004/II/2023', 'supir_id' => '298', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '215736', 'keterangan' => 'GAJI MINUS SUPIR SULAIMAN B 9668 QZ TGL. 01 FEBRUARI 2023', 'modifiedby' => 'ADMIN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '5', 'nobukti' => 'PJT 0017/I/2023', 'supir_id' => '164', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '20948', 'keterangan' => '(KAMAL)Gaji Minus Supir Kamal BK 8050 CJ Tgl. 24 Januari 2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '6', 'nobukti' => 'PJT 0018/III/2022', 'supir_id' => '172', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '479115', 'keterangan' => '(Liberto)Tagih Supir Liberto atas Biaya Tembus Closing shipper Usaha Rajin ', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '7', 'nobukti' => 'PJT 0039/VIII/2022', 'supir_id' => '215', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '11611000', 'keterangan' => '(NG BIN SAN)Pinjaman Bp. Asan untuk Biaya Demurage Periode Desember 2021 - 05 Juli 2022 sebesar Rp. 11.611.000 ( Dipotong dari fee Rp. 1.000.000 / Bln, Dimulai sesudah Pinjaman yng lama habis dipotong )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '8', 'nobukti' => 'PJT 0043/VI/2022', 'supir_id' => '215', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '12910000', 'keterangan' => '(NG BIN SAN)Pinjaman Bp. Asan untuk Biaya Demurage Periode Desember 2021 - 31 Mei 2022 sebesar Rp. 19.910.000 ( Dipotong dari fee Rp. 1.000.000 / Bln, Mulai Bln Juni 2022 )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '9', 'nobukti' => 'PJT 0008/I/2023', 'supir_id' => '244', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '600304', 'keterangan' => '(RAMADANI GINTING)Pinjaman Supir Ramadani atas Biaya Isi BBM Trado Tgl. 10 Januari 2023 untuk proses Hutang BBM yang belakangan diisi untuk Tgl. 23 Desember 2022 RIC 0133/XII/2022', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '10', 'nobukti' => 'PJT 0040/XII/2022', 'supir_id' => '244', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '1087587', 'keterangan' => '(RAMADANI GINTING)Gaji Minus Supir Ramadani BK 8747 BU Tgl. 21 Desember 2022', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '11', 'nobukti' => 'PJT 0020/I/2023', 'supir_id' => '298', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '400000', 'keterangan' => '(SULAIMAN)Biaya Isi BBM Trado Tgl. 19 Januari 2023 untuk proses Hutang BBM A/N Sulaiman  ( Bayar cash karena SPBU PT. Ronatama Agro Migas  BBM kosong ), dijadikan PJT karena ada kesalahan tidak terinput di RIC 0098/I/2023', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '12', 'nobukti' => 'PJT 0015/XII/2022', 'supir_id' => '71', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '300000', 'keterangan' => '(DEWANTO PURBA (EX)) Pinjaman Supir Dewanto atas Denda untuk Absen tidak masuk kerja Bulan November 2022 ( Tgl. 03, 15 Off, Tgl. 16,17,18,25,28,29,30 @ Rp. 100.000, Tgl. 19,26 @ Rp. 200.000, Tgl. 06,07 Desember 2022 )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '13', 'nobukti' => 'PJT 0001/XII/2022', 'supir_id' => '73', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '239750', 'keterangan' => '(DIMAS AGUNG PRABOWO)KLAIM SUPIR DIMAS AGUNG B 9120 QZ ATAS PEMBELIAN SPAREPART UNTUK SISIP MOBIL YANG KECELAKAAN  SEBESAR RP.436.000 (SPK 0002/XI/2022)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '14', 'nobukti' => 'PJT 0004/VIII/2022', 'supir_id' => '73', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '102050', 'keterangan' => '(DIMAS AGUNG PRABOWO)Charge supir Dimas Agung atas Ban Masak yg Meledak pada Gandengan T-70 Pendek dgn no 1100 - 05003307 ketebalan 5mm sebesar Rp.525.833 + Rp.500.000 (Biaya Vul 2)  total keseluruhan Rp. 1.025.833 Dibula', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '15', 'nobukti' => 'PJT 0037/X/2022', 'supir_id' => '73', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '555250', 'keterangan' => '(DIMAS AGUNG PRABOWO)Pinjaman Supir Dimas Agung atas Biaya Perbaikan di Gudang PT. MSI karena nabrak pembatas ', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '16', 'nobukti' => 'PJT 0049/XII/2022', 'supir_id' => '73', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '80750', 'keterangan' => '(DIMAS AGUNG PRABOWO)KLAIM SUPIR DIMAS AGUNG ATAS LAMPU STOP YG HILANG DAN KACA SPION PETAK BESAR YG PECAH DIBUAT SUPIR SEBESAR RP.162.000 (SPK 0087/XII/2022)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '17', 'nobukti' => 'PJT 0021/XII/2022', 'supir_id' => '146', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '675800', 'keterangan' => '(JANTO)Charge supir Janto atas Ban Masak yg Rusak/Lepas Bunga pada B 9508 PH dgn no ban 1100  06415111 ketebalan 5mm sebesar Rp.525.833 + Rp.500.000 (Biaya Vul 2), total keseluruhan Rp. 1.025.833 Dibulatkan', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '20', 'nobukti' => 'PJT 0022/VII/2022', 'supir_id' => '172', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '839615', 'keterangan' => '(Liberto)Charge supir Liberto atas Ban Masak yg Meledak pada Gandengan T-08 Panjang dgn no 1100 - 06301214 ketebalan 6mm sebesar Rp.609.000 + Rp.500.000 (Biaya Vul 2)  total keseluruhan Rp. 1.109.000 dengan pe', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '21', 'nobukti' => 'PJT 0023/VII/2022', 'supir_id' => '172', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '70615', 'keterangan' => '(Liberto)Ganti Ban Dalam Karena Ban Meledak Pada Gandengan T-08 Panjang Sebesar RP.340.000 Supir Liberto', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '18', 'nobukti' => 'PJT 0006/IX/2015', 'supir_id' => '172', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '9439545', 'keterangan' => '(Liberto)Potong Pinjaman atas Pelunasan biaya penyewaan crane,perbaikan warung & Trado BK 8596 LU akibat kecelakaan Liberto', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '19', 'nobukti' => 'PJT 0014/I/2019', 'supir_id' => '172', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '46875', 'keterangan' => '(Liberto)Biaya perbaikan 2 unit losbak yang di tabrak Trado 8596 LU supir Liberto (Charge supir Liberto)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '22', 'nobukti' => 'PJT 0070/VIII/2019', 'supir_id' => '172', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '1838994', 'keterangan' => '(Liberto)GANTI PERBAIKAN POMPA PUM SEBESAR Rp.3.565.000,-  AKIBAT KELALAIAN SUPIR LIBERTO (BK 8596 LU)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '23', 'nobukti' => 'PJT 0036/XII/2022', 'supir_id' => '244', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '244484', 'keterangan' => '(RAMADANI GINTING)KLAIM SUPIR RAMADANI GINTING ATAS KACA KABIN BELAKANG YG PECAH DIBUAT SUPIR SEBESAR RP.250.000 (SPK 0071/XII/2022)', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '24', 'nobukti' => 'PJT 0044/XI/2022', 'supir_id' => '267', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '15502369', 'keterangan' => '(SAHBUDIN)Setor ke Pancaran Jatinusa atas Biaya Repairing Container CAIU 4636498, TXGU 5303991 yang jatuh ditabrak oleh Supir Sahbudin sebesar Rp. 16.642.369,- ( Dijadikan PJT Supir )', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '74', 'nobukti' => 'PJT 0046/III/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '205000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-33 Panjang  sebesar Rp.285.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '75', 'nobukti' => 'PJT 0047/XI/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '290000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-30 Panjang dgn no ban 1100 - 0820110-2 sebesar Rp.300.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '76', 'nobukti' => 'PJT 0048/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '590000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang RUSAK dengan no ban 1100 - 1906303 pada Gandengan T-07 Panjang sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '77', 'nobukti' => 'PJT 0048/XI/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '490000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-51 Panjang dgn no ban 1100 - 04918304 sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '78', 'nobukti' => 'PJT 0049/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '690000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04918306 yang hilang pada Gandengan T-32 Panjang sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '79', 'nobukti' => 'PJT 0050/II/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '380000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-72 Panjang  sebesar Rp.400.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '80', 'nobukti' => 'PJT 0052/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '508452', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1013305  pada Gandengan T-16 Panjang setebal 6mm sebesar Rp.600.000,- dibagi 18 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '81', 'nobukti' => 'PJT 0054/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '690000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1013312 yang hilang pada Gandengan T-08 Panjang sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '82', 'nobukti' => 'PJT 0055/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '790000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 0210311 yang hilang pada Gandengan T-62 Panjang sebesar Rp.800.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '83', 'nobukti' => 'PJT 0057/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '735000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04922301  pada Gandengan T-31 Panjang setebal 8mm sebesar Rp.800.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '71', 'nobukti' => 'PJT 0037/III/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '320000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang afkir dgn no ban 1100-0804106  pada Gandengan T-57 PENDEK  sebesar Rp.400.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '72', 'nobukti' => 'PJT 0037/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '590000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dengan no ban 1100 - 02105301 pada Gandengan T-23 Panjang sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '73', 'nobukti' => 'PJT 0038/XII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '400000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-25 Panjang dgn no ban 1100 - 2015206  sebesar Rp.400.000,- dibagi 15 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '55', 'nobukti' => 'PJT 0023/VII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '683922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 0818307 pada Gandengan T-46 Panjang sebesar Rp.700.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '54', 'nobukti' => 'PJT 0022/IV/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '663922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T- 13 Panjang dgn no ban 1100 - 2008207 setebal 7mm sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '56', 'nobukti' => 'PJT 0026/I/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '345000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas ban yang meledak pada Gandengan T-64 Pendek  sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '57', 'nobukti' => 'PJT 0026/IV/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '383922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Rusak/Koyak Besar pada Gandengan T- 51 Panjang dgn no ban 1100 - 0925207 setebal 4mm sebesar Rp.400.000,- dibagi 19 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '58', 'nobukti' => 'PJT 0027/I/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '235000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-43 Panjang  sebesar Rp.275.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '59', 'nobukti' => 'PJT 0028/II/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '360000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-45 Panjang  sebesar Rp.400.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '60', 'nobukti' => 'PJT 0028/III/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '563922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 2003303 pada Gandengan T- 01 Panjang sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '61', 'nobukti' => 'PJT 0028/IV/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '783922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T- 45 Panjang dgn no ban 1100 - 2008114 setebal 8mm sebesar Rp.800.000,- dibagi 19 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '62', 'nobukti' => 'PJT 0029/IV/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '783922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Rusak/Lepas Bunga pada Gandengan T- 45 Panjang dgn no ban 1100 - 1908208 setebal 8mm sebesar Rp.800.000,- dibagi 19 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '63', 'nobukti' => 'PJT 0030/I/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '1080000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas ban yang meledak pada Gandengan T-30 Panjang  sebesar Rp.1.100.000,- dibagi 16 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '64', 'nobukti' => 'PJT 0030/III/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '763922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1019202 pada Gandengan T- 53 Panjang sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '65', 'nobukti' => 'PJT 0032/VII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '783922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 06321311 pada Gandengan T-18 Panjang sebesar Rp.800.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '66', 'nobukti' => 'PJT 0033/III/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '463922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 1017209 pada Gandengan T- 60 Pendek sebesar Rp.500.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '67', 'nobukti' => 'PJT 0034/VIII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '258922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-44 Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '68', 'nobukti' => 'PJT 0034/XII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '275000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-03 Panjang  sebesar Rp.275.000,- dibagi 15 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '69', 'nobukti' => 'PJT 0035/I/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '255000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-37 Panjang  sebesar Rp.275.000,- dibagi 16 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '70', 'nobukti' => 'PJT 0036/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '790000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dengan no ban 1100 - 04923201 pada Gandengan T-39 Panjang sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '28', 'nobukti' => 'PJT 0003/II/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '460000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-22 Panjang  sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '29', 'nobukti' => 'PJT 0003/VII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '783922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-36 Panjang dgn no ban 1100 - 0910105 sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '30', 'nobukti' => 'PJT 0004/III/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '225000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-33 Panjang  sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '42', 'nobukti' => 'PJT 0015/III/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '40000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 07 Panjang sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '43', 'nobukti' => 'PJT 0015/III/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '105000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-62 Panjang  sebesar Rp.285.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '44', 'nobukti' => 'PJT 0015/IX/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '583922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak dengan no ban 1100 - 0803214-1 pada Gandengan T-51 Panjang sebesar Rp.600.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '45', 'nobukti' => 'PJT 0015/V/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '238922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 24 Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '46', 'nobukti' => 'PJT 0016/III/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '112354', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 07 Panjang sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '47', 'nobukti' => 'PJT 0016/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '500000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak pada Gandengan T-46 Panjang dgn no ban 1100 - 0210312  sebesar Rp.600.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '48', 'nobukti' => 'PJT 0016/VIII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '383922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak/lepas bunga dgn no ban 1100 - 0829209 pada Gandengan T-48 Pendek sebesar Rp.400.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '49', 'nobukti' => 'PJT 0017/III/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '688922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04924112 pada Gandengan T- 07 Panjang sebesar Rp.740.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '50', 'nobukti' => 'PJT 0019/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '210000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-35 Panjang  sebesar Rp.270.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '51', 'nobukti' => 'PJT 0020/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '740000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 06523105  pada Gandengan T-01 Panjang  sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '52', 'nobukti' => 'PJT 0020/XII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '490000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-64 Pendek dgn no ban 1100 - 02118305 sebesar Rp.500.000,- dibagi 15 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '53', 'nobukti' => 'PJT 0021/XII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '590000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-05 Panjang dgn no ban 1100 - 1008313 sebesar Rp.600.000,- dibagi 15 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '34', 'nobukti' => 'PJT 0007/X/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '265000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-67 Pendek sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '35', 'nobukti' => 'PJT 0008/VI/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '783922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-45 Panjang dgn no ban 1100 - 1908205 sebesar Rp.800.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '36', 'nobukti' => 'PJT 0009/III/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '225000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang  pada Gandengan T-14 Panjang  sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '37', 'nobukti' => 'PJT 0009/VII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '258922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-27 Panjang sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '38', 'nobukti' => 'PJT 0010/IV/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '158922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 62Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '39', 'nobukti' => 'PJT 0010/VII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '158922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-46 Panjang sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '40', 'nobukti' => 'PJT 0011/VII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '258922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-46 Panjang sebesar Rp.275.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '41', 'nobukti' => 'PJT 0013/X/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '590000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang lepas bunga pada Gandengan T-19 Panjang dgn no ban 1100 - 06309303 sebesar Rp.600.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '31', 'nobukti' => 'PJT 0005/IV/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '228922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T- 21 Panjang sebesar Rp.285.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '32', 'nobukti' => 'PJT 0005/X/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '265000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Lock Gandengan yang hilang pada Gandengan T-08 Panjang sebesar Rp.275.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '33', 'nobukti' => 'PJT 0006/III/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '725000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak  pada Gandengan T-17 Panjang  sebesar Rp.805.000,- dibagi 17 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '25', 'nobukti' => 'PJT 0001/VI/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '663922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang rusak pada Gandengan T-16 Panjang dgn no ban 1100 - 01020101 sebesar Rp.700.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '26', 'nobukti' => 'PJT 0001/VIII/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '463922', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 2016207 pada Gandengan T-34 Panjang sebesar Rp.500.000,- dibagi 18 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '27', 'nobukti' => 'PJT 0001/XI/2018', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '490000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang Meledak pada Gandengan T-28 Pendek dgn no ban 1100 - 02118214 sebesar Rp.500.000,- dibagi 16 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '85', 'nobukti' => 'PJT 0080/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '720000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 04918310  pada Gandengan T-18 Panjang setebal 8mm sebesar Rp.800.000,- dibagi 18 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '86', 'nobukti' => 'PJT 0081/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '740000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 06315116  pada Gandengan T-62 Panjang setebal 8mm sebesar Rp.800.000,- dibagi 18 supi', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '84', 'nobukti' => 'PJT 0066/IV/2019', 'supir_id' => '0', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '660000', 'keterangan' => '(SEMUA)Charge bersama semua supir atas Ban yang meledak dgn no ban 1100 - 01028301 pada Gandengan T-16 Panjang setebal 7mm sebesar Rp.700.000,- dibagi 17 supir', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '87', 'nobukti' => 'PJT 0014/X/2022', 'supir_id' => '305', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '662000', 'keterangan' => '(SYAFRIZAL)Charge supir Syafrizal atas Ban Masak yg meledak Panjang dgn no 1100  06425101 ketebalan 6mm sebesar Rp.661.999 + Rp.500.000 (Biaya Vul 2)  total keseluruhan Rp. 1.161.999 Dibulatkan menjadi Rp.1.162', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '88', 'nobukti' => 'PJT 0002/XII/2022', 'supir_id' => '307', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '665700', 'keterangan' => '(SYAIFUL BAHRI LUBIS)Charge supir Syaiful atas Ban Masak yg Rusak Jebol Samping pada B 9949 JH dgn no ban 1100 - 06316109 ketebalan 4mm sebesar Rp.420.666 + Rp.500.000 (Biaya Vul 2), total keseluruhan Rp. 920.666 Dibulatk', 'modifiedby' => 'RYAN',]);
        pengeluarantruckingdetail::create(['pengeluarantruckingheader_id' => '89', 'nobukti' => 'PJT 0062/XI/2022', 'supir_id' => '307', 'penerimaantruckingheader_nobukti' => '', 'nominal' => '7182500', 'keterangan' => '(SYAIFUL BAHRI LUBIS)Pinjaman Supir Syaiful B 9949 JH untuk Biaya Perdamaian, Kepolisian dan Ibu Sidabutar atas Laka di Tebing Tinggi', 'modifiedby' => 'RYAN',]);
    }
}
