<?php

namespace Database\Seeders;

use App\Models\Subkelompok;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubKelompokSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("delete Subkelompok");
        DB::statement("DBCC CHECKIDENT ('Subkelompok', RESEED, 1);");

        subkelompok::create(['kodesubkelompok' => 'AIR', 'keterangan' => 'AIR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AKI', 'keterangan' => 'AKI', 'kelompok_id' => '3', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AKI', 'keterangan' => 'AKI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ALARM', 'keterangan' => 'ALARM', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ALAS', 'keterangan' => 'ALAS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AMPERE', 'keterangan' => 'AMPERE', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AMRIL', 'keterangan' => 'AMRIL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ANAK SHOCK', 'keterangan' => 'ANAK SHOCK', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ANGKER', 'keterangan' => 'ANGKER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AS', 'keterangan' => 'AS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AXLE', 'keterangan' => 'AXLE', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'AYUNAN', 'keterangan' => 'AYUNAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BAN DALAM', 'keterangan' => 'BAN DALAM', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BAN LUAR', 'keterangan' => 'BAN LUAR', 'kelompok_id' => '1', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BAN LUAR', 'keterangan' => 'BAN LUAR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BATU', 'keterangan' => 'BATU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BAUT', 'keterangan' => 'BAUT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BENDIT', 'keterangan' => 'BENDIT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BESI', 'keterangan' => 'BESI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BLOCK', 'keterangan' => 'BLOCK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BOHEL', 'keterangan' => 'BOHEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BOLA LAMPU', 'keterangan' => 'BOLA LAMPU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BOLU-BOLU', 'keterangan' => 'BOLU-BOLU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BOSING', 'keterangan' => 'BOSING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BOTOL', 'keterangan' => 'BOTOL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BUSHING', 'keterangan' => 'BUSHING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'BUSI', 'keterangan' => 'BUSI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'CAT', 'keterangan' => 'CAT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'CATRICK', 'keterangan' => 'CATRICK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'CHAMBER', 'keterangan' => 'CHAMBER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'CLEANER', 'keterangan' => 'CLEANER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'COK KABEL GANDENGAN', 'keterangan' => 'COK KABEL GANDENGAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'COMPRESSOR', 'keterangan' => 'COMPRESSOR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DASHBOARD', 'keterangan' => 'DASHBOARD', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DAUN', 'keterangan' => 'DAUN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DEMPUL', 'keterangan' => 'DEMPUL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DEXEL', 'keterangan' => 'DEXEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DINAMO', 'keterangan' => 'DINAMO', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DONGKRAK', 'keterangan' => 'DONGKRAK', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DONGKRAK', 'keterangan' => 'DONGKRAK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DOOR', 'keterangan' => 'DOOR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DOOR LOCK', 'keterangan' => 'DOOR LOCK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DOOR TRIM', 'keterangan' => 'DOOR TRIM', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DRAIN', 'keterangan' => 'DRAIN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'DRAKLINK', 'keterangan' => 'DRAKLINK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ELBO', 'keterangan' => 'ELBO', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ENGKOL', 'keterangan' => 'ENGKOL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ENGSEL', 'keterangan' => 'ENGSEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'FILTER', 'keterangan' => 'FILTER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GAGANG', 'keterangan' => 'GAGANG', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GAGANG', 'keterangan' => 'GAGANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GEMBOK', 'keterangan' => 'GEMBOK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GIGI', 'keterangan' => 'GIGI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GOVERNOR', 'keterangan' => 'GOVERNOR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GRENDA', 'keterangan' => 'GRENDA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GRILL', 'keterangan' => 'GRILL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GULI GULI HANDLE', 'keterangan' => 'GULI GULI HANDLE', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'GUN', 'keterangan' => 'GUN', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'HANDLE', 'keterangan' => 'HANDLE', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ISI', 'keterangan' => 'ISI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'JEMBER', 'keterangan' => 'JEMBER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'JOK', 'keterangan' => 'JOK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KABEL', 'keterangan' => 'KABEL', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KABEL', 'keterangan' => 'KABEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KABIN', 'keterangan' => 'KABIN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KACA', 'keterangan' => 'KACA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KAIN', 'keterangan' => 'KAIN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KAIN KLOS', 'keterangan' => 'KAIN KLOS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KAKI ', 'keterangan' => 'KAKI ', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KAKI MESIN', 'keterangan' => 'KAKI MESIN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KANVAS', 'keterangan' => 'KANVAS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KARET', 'keterangan' => 'KARET', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KAWAT', 'keterangan' => 'KAWAT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KAYU', 'keterangan' => 'KAYU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KEPALA', 'keterangan' => 'KEPALA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KERTAS', 'keterangan' => 'KERTAS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KING PEN', 'keterangan' => 'KING PEN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KIPAS', 'keterangan' => 'KIPAS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KIT', 'keterangan' => 'KIT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KLAKSON', 'keterangan' => 'KLAKSON', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KLEMAN', 'keterangan' => 'KLEMAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KLEP', 'keterangan' => 'KLEP', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KNALPOT', 'keterangan' => 'KNALPOT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KOPLING', 'keterangan' => 'KOPLING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KRAN', 'keterangan' => 'KRAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KUDA KEPANG', 'keterangan' => 'KUDA KEPANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KUNCI', 'keterangan' => 'KUNCI', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'KUNCI', 'keterangan' => 'KUNCI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LAHAR', 'keterangan' => 'LAHAR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LAMPU', 'keterangan' => 'LAMPU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LANGIT', 'keterangan' => 'LANGIT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LAPIS / PLAT', 'keterangan' => 'LAPIS / PLAT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LEM', 'keterangan' => 'LEM', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LENA', 'keterangan' => 'LENA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'LOCK', 'keterangan' => 'LOCK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MATA', 'keterangan' => 'MATA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MATAHARI', 'keterangan' => 'MATAHARI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MENTALAN', 'keterangan' => 'MENTALAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MESIN', 'keterangan' => 'MESIN', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MESIN', 'keterangan' => 'MESIN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MINYAK', 'keterangan' => 'MINYAK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MULTITESTER', 'keterangan' => 'MULTITESTER', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MUR', 'keterangan' => 'MUR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'MUR GANDENGAN', 'keterangan' => 'MUR GANDENGAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'NEPEL', 'keterangan' => 'NEPEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'NOZLE', 'keterangan' => 'NOZLE', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'OBENG', 'keterangan' => 'OBENG', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'OBENG', 'keterangan' => 'OBENG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'OLI', 'keterangan' => 'OLI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'OLI SEAL', 'keterangan' => 'OLI SEAL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ORING', 'keterangan' => 'ORING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PACKING', 'keterangan' => 'PACKING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PAHA', 'keterangan' => 'PAHA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PAKAM', 'keterangan' => 'PAKAM', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PAKU', 'keterangan' => 'PAKU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PANEL', 'keterangan' => 'PANEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PAWON', 'keterangan' => 'PAWON', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PEN', 'keterangan' => 'PEN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PEN PER', 'keterangan' => 'PEN PER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PENTA', 'keterangan' => 'PENTA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PER', 'keterangan' => 'PER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PERALATAN MEKANIK', 'keterangan' => 'PERALATAN MEKANIK', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PESAWAT', 'keterangan' => 'PESAWAT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PIPA', 'keterangan' => 'PIPA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PIPI', 'keterangan' => 'PIPI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PIRING', 'keterangan' => 'PIRING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PISAU', 'keterangan' => 'PISAU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PISTON', 'keterangan' => 'PISTON', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PLAT', 'keterangan' => 'PLAT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'POMPA', 'keterangan' => 'POMPA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PORSNELING', 'keterangan' => 'PORSNELING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PRESS', 'keterangan' => 'PRESS', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PRESS', 'keterangan' => 'PRESS', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'PUTARAN', 'keterangan' => 'PUTARAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'RADIATOR', 'keterangan' => 'RADIATOR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'REM', 'keterangan' => 'REM', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'REPAIR KIT', 'keterangan' => 'REPAIR KIT', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'RING', 'keterangan' => 'RING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'RODA', 'keterangan' => 'RODA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'ROTOR', 'keterangan' => 'ROTOR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'RUMAH', 'keterangan' => 'RUMAH', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SAFETY', 'keterangan' => 'SAFETY', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SAKLAR', 'keterangan' => 'SAKLAR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SALAMAN', 'keterangan' => 'SALAMAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SARANG', 'keterangan' => 'SARANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEAL', 'keterangan' => 'SEAL', 'kelompok_id' => '0', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEAL', 'keterangan' => 'SEAL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEAL KLEP', 'keterangan' => 'SEAL KLEP', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEGITIGA', 'keterangan' => 'SEGITIGA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEKRAP', 'keterangan' => 'SEKRAP', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEKRUP', 'keterangan' => 'SEKRUP', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SELANG', 'keterangan' => 'SELANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SELENDANG', 'keterangan' => 'SELENDANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SEPATU', 'keterangan' => 'SEPATU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SHOCK', 'keterangan' => 'SHOCK', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SHOCK', 'keterangan' => 'SHOCK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SIKU', 'keterangan' => 'SIKU', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SILANG', 'keterangan' => 'SILANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SINGKRON', 'keterangan' => 'SINGKRON', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SINKRON', 'keterangan' => 'SINKRON', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SOKET', 'keterangan' => 'SOKET', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SOLAR', 'keterangan' => 'SOLAR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SOLASIBAN', 'keterangan' => 'SOLASIBAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SOLDER', 'keterangan' => 'SOLDER', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SPION', 'keterangan' => 'SPION', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'STANG LAS', 'keterangan' => 'STANG LAS', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'STEMPEL', 'keterangan' => 'STEMPEL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'SWITCH', 'keterangan' => 'SWITCH', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TABUNG', 'keterangan' => 'TABUNG', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TABUNG', 'keterangan' => 'TABUNG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TALI', 'keterangan' => 'TALI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TANDUK', 'keterangan' => 'TANDUK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TANG', 'keterangan' => 'TANG', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TANG', 'keterangan' => 'TANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TANGGA', 'keterangan' => 'TANGGA', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TANGKI', 'keterangan' => 'TANGKI', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TAP', 'keterangan' => 'TAP', 'kelompok_id' => '4', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TAP', 'keterangan' => 'TAP', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TAPAK', 'keterangan' => 'TAPAK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'THOMSOL', 'keterangan' => 'THOMSOL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TIANG', 'keterangan' => 'TIANG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TIEROD', 'keterangan' => 'TIEROD', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TIMAH SOLDER', 'keterangan' => 'TIMAH SOLDER', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TOMBOL', 'keterangan' => 'TOMBOL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TPO', 'keterangan' => 'TPO', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TROMOL', 'keterangan' => 'TROMOL', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'TUTUP', 'keterangan' => 'TUTUP', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'VALVE REM TANGAN', 'keterangan' => 'VALVE REM TANGAN', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'VELG', 'keterangan' => 'VELG', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'VELVE', 'keterangan' => 'VELVE', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'VORING', 'keterangan' => 'VORING', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'WAYAR', 'keterangan' => 'WAYAR', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
        subkelompok::create(['kodesubkelompok' => 'WIPER LINK', 'keterangan' => 'WIPER LINK', 'kelompok_id' => '2', 'statusaktif' => '1', 'modifiedby' => 'ADMIN',]);
    }
}
