<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UpahRitasiRincian;
use Illuminate\Support\Facades\DB;

class UpahRitasiRincianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("delete UpahRitasiRincian");
        DB::statement("DBCC CHECKIDENT ('UpahRitasiRincian', RESEED, 1);");

        upahritasirincian::create(['upahritasi_id' => '1', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '2', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '2.77', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '3', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '4', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '5', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '1.45', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '6', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '7', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '8', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '2.77', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '9', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '20.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '10', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '11', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '12', 'container_id' => '1', 'nominalsupir' => '18600.00', 'liter' => '8.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '13', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '14', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '40.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '15', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '16', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '3.78', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '17', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '18', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '19', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '5.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '20', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '5.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '21', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '22', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '23', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '5.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '24', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '2.78', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '25', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '1.45', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '26', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '7.33', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '27', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '8.78', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '28', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '29', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '30', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '4.56', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '31', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '2.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '32', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '33', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '34', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '35', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '36', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '37', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '4.56', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '38', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '39', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '40', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '7.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '41', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '42', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '1.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '43', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '44', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '45', 'container_id' => '1', 'nominalsupir' => '30900.00', 'liter' => '3.78', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '46', 'container_id' => '1', 'nominalsupir' => '51000.00', 'liter' => '5.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '47', 'container_id' => '1', 'nominalsupir' => '51000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '48', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '2.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '49', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '50', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '51', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '52', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '53', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '5.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '54', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '54', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '55', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '55', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '56', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '57', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '58', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '59', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '3.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '60', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '2.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '61', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '62', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '1.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '63', 'container_id' => '1', 'nominalsupir' => '41000.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '64', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '65', 'container_id' => '1', 'nominalsupir' => '51200.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '66', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '67', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '68', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '69', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '70', 'container_id' => '1', 'nominalsupir' => '30900.00', 'liter' => '3.78', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '71', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '72', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '73', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '4.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '73', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '74', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '4.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '74', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '1.67', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '75', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '76', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '2.50', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '77', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '78', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '78', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '79', 'container_id' => '1', 'nominalsupir' => '51000.00', 'liter' => '42.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '80', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '80', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '81', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '30.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '82', 'container_id' => '1', 'nominalsupir' => '27400.00', 'liter' => '40.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '83', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '2.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '84', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '2.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '85', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '1.65', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '86', 'container_id' => '1', 'nominalsupir' => '30900.00', 'liter' => '7.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '87', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '88', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '3.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '89', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '90', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '91', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '92', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '2.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '93', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '94', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '95', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '96', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '97', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '98', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '99', 'container_id' => '1', 'nominalsupir' => '6800.00', 'liter' => '8.90', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '100', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '101', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '102', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '103', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '104', 'container_id' => '1', 'nominalsupir' => '40800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '105', 'container_id' => '1', 'nominalsupir' => '51200.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '106', 'container_id' => '1', 'nominalsupir' => '47600.00', 'liter' => '22.50', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '107', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '2.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '108', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '109', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '110', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '111', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '112', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '113', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '114', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '2.50', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '115', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '40.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '116', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '1.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '117', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '118', 'container_id' => '1', 'nominalsupir' => '20400.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '119', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '120', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '121', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '122', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '123', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '124', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '125', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '126', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '127', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '40.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '128', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '7.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '129', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '47.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '130', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '131', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '132', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '20.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '133', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '134', 'container_id' => '1', 'nominalsupir' => '17000.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '135', 'container_id' => '1', 'nominalsupir' => '34000.00', 'liter' => '45.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '136', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '20.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '137', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '70.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '138', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '4.44', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '139', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '22.50', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '140', 'container_id' => '1', 'nominalsupir' => '30800.00', 'liter' => '20.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '141', 'container_id' => '1', 'nominalsupir' => '13600.00', 'liter' => '20.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '142', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '30.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '143', 'container_id' => '1', 'nominalsupir' => '37600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '144', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '12.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '144', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '14.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '145', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '12.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '145', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '14.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '146', 'container_id' => '1', 'nominalsupir' => '18600.00', 'liter' => '0.89', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '147', 'container_id' => '1', 'nominalsupir' => '0.00', 'liter' => '2.22', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '148', 'container_id' => '1', 'nominalsupir' => '27400.00', 'liter' => '3.11', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '149', 'container_id' => '1', 'nominalsupir' => '35600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '149', 'container_id' => '1', 'nominalsupir' => '35600.00', 'liter' => '6.56', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '150', 'container_id' => '1', 'nominalsupir' => '35600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '150', 'container_id' => '1', 'nominalsupir' => '35600.00', 'liter' => '6.56', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '151', 'container_id' => '1', 'nominalsupir' => '18600.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '152', 'container_id' => '1', 'nominalsupir' => '50300.00', 'liter' => '7.33', 'modifiedby' => 'RYAN',]);
        upahritasirincian::create(['upahritasi_id' => '153', 'container_id' => '1', 'nominalsupir' => '23800.00', 'liter' => '0.00', 'modifiedby' => 'RYAN',]);
    }
}
