<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UpahRitasi;
use Illuminate\Support\Facades\DB;

class UpahRitasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        
        DB::statement("delete UpahRitasi");
        DB::statement("DBCC CHECKIDENT ('UpahRitasi', RESEED, 1);");

        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '4', 'nominalsupir' => '0.00', 'jarak' => '15.40', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '7.44', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '57', 'nominalsupir' => '0.00', 'jarak' => '16.40', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '130', 'nominalsupir' => '0.00', 'jarak' => '14.10', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '16.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '134', 'nominalsupir' => '0.00', 'jarak' => '13.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '22', 'nominalsupir' => '0.00', 'jarak' => '14.80', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '41', 'nominalsupir' => '0.00', 'jarak' => '14.50', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '21', 'nominalsupir' => '0.00', 'jarak' => '13.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '42', 'nominalsupir' => '0.00', 'jarak' => '14.50', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '29', 'kotasampai_id' => '125', 'nominalsupir' => '0.00', 'jarak' => '18.80', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '1', 'kotasampai_id' => '3', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '1', 'kotasampai_id' => '129', 'nominalsupir' => '0.00', 'jarak' => '20.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '1', 'kotasampai_id' => '62', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '1', 'kotasampai_id' => '17', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '27.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '32.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '22', 'nominalsupir' => '0.00', 'jarak' => '16.70', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '40', 'nominalsupir' => '0.00', 'jarak' => '11.20', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '19', 'nominalsupir' => '0.00', 'jarak' => '24.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '21', 'nominalsupir' => '0.00', 'jarak' => '31.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '34', 'kotasampai_id' => '42', 'nominalsupir' => '0.00', 'jarak' => '27.70', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '29', 'nominalsupir' => '0.00', 'jarak' => '14.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '34', 'nominalsupir' => '0.00', 'jarak' => '30.30', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '55', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '4', 'nominalsupir' => '0.00', 'jarak' => '7.20', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '2.70', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '57', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '130', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '22', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '3', 'kotasampai_id' => '19', 'nominalsupir' => '0.00', 'jarak' => '7.20', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '5', 'kotasampai_id' => '3', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '5', 'kotasampai_id' => '31', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '5', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '7.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '5', 'kotasampai_id' => '27', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '5', 'kotasampai_id' => '93', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '29', 'nominalsupir' => '0.00', 'jarak' => '7.40', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '1', 'nominalsupir' => '0.00', 'jarak' => '20.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '128', 'nominalsupir' => '0.00', 'jarak' => '20.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '34', 'nominalsupir' => '0.00', 'jarak' => '23.70', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '35', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '3', 'nominalsupir' => '0.00', 'jarak' => '3.10', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '9.30', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '33', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '55', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '4', 'nominalsupir' => '0.00', 'jarak' => '13.90', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '31', 'nominalsupir' => '0.00', 'jarak' => '23.70', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '3.60', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '3.60', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '9', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '57', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '10', 'nominalsupir' => '0.00', 'jarak' => '6.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '62', 'nominalsupir' => '0.00', 'jarak' => '3.10', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '11', 'nominalsupir' => '0.00', 'jarak' => '3.60', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '12', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '27', 'nominalsupir' => '0.00', 'jarak' => '7.40', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '13', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '36', 'nominalsupir' => '0.00', 'jarak' => '45.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '71', 'nominalsupir' => '0.00', 'jarak' => '13.90', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '38', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '3.60', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '133', 'nominalsupir' => '0.00', 'jarak' => '13.90', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '126', 'nominalsupir' => '0.00', 'jarak' => '20.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '80', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '130', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '8.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '13.90', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '17', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '18', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '22', 'nominalsupir' => '0.00', 'jarak' => '10.40', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '41', 'nominalsupir' => '0.00', 'jarak' => '10.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '40', 'nominalsupir' => '0.00', 'jarak' => '84.70', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '41', 'nominalsupir' => '0.00', 'jarak' => '10.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '19', 'nominalsupir' => '0.00', 'jarak' => '6.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '21', 'nominalsupir' => '0.00', 'jarak' => '13.60', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '42', 'nominalsupir' => '0.00', 'jarak' => '18.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '132', 'nominalsupir' => '0.00', 'jarak' => '18.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '93', 'nominalsupir' => '0.00', 'jarak' => '3.30', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '104', 'kotasampai_id' => '127', 'nominalsupir' => '0.00', 'jarak' => '13.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '59', 'kotasampai_id' => '104', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '57', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '14.90', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '55', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '3.10', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '57', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '130', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '22', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '62', 'kotasampai_id' => '19', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '11', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '3.60', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '27', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '27', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '27', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '36', 'kotasampai_id' => '29', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '36', 'kotasampai_id' => '31', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '36', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '45.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '36', 'kotasampai_id' => '34', 'nominalsupir' => '0.00', 'jarak' => '36.60', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '71', 'kotasampai_id' => '21', 'nominalsupir' => '0.00', 'jarak' => '3.80', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '38', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '38', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '38', 'kotasampai_id' => '36', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '38', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '38', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '38', 'kotasampai_id' => '19', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '14', 'kotasampai_id' => '104', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '24', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '8.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '24', 'kotasampai_id' => '41', 'nominalsupir' => '0.00', 'jarak' => '1.89', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '50', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '55', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '57', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '15', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '130', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '22', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '17', 'kotasampai_id' => '19', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '22', 'kotasampai_id' => '34', 'nominalsupir' => '0.00', 'jarak' => '14.30', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '22', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '14.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '4', 'nominalsupir' => '0.00', 'jarak' => '14.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '40', 'kotasampai_id' => '36', 'nominalsupir' => '0.00', 'jarak' => '45.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '29', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '33', 'nominalsupir' => '0.00', 'jarak' => '27.90', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '37.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '27', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '36', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '71', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '131', 'nominalsupir' => '0.00', 'jarak' => '27.50', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '21', 'nominalsupir' => '0.00', 'jarak' => '8.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '41', 'kotasampai_id' => '42', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '19', 'kotasampai_id' => '29', 'nominalsupir' => '0.00', 'jarak' => '15.10', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '19', 'kotasampai_id' => '3', 'nominalsupir' => '0.00', 'jarak' => '12.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '19', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '6.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '19', 'kotasampai_id' => '27', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '19', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '19', 'kotasampai_id' => '24', 'nominalsupir' => '0.00', 'jarak' => '12.50', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '21', 'kotasampai_id' => '29', 'nominalsupir' => '0.00', 'jarak' => '9.50', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '21', 'kotasampai_id' => '5', 'nominalsupir' => '0.00', 'jarak' => '9.50', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '21', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '10.50', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '21', 'kotasampai_id' => '36', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '21', 'kotasampai_id' => '36', 'nominalsupir' => '0.00', 'jarak' => '22.70', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '21', 'kotasampai_id' => '38', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '1', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '42', 'kotasampai_id' => '6', 'nominalsupir' => '0.00', 'jarak' => '23.80', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);
        upahritasi::create([ 'parent_id' => '0', 'tarif_id' => '0', 'kotadari_id' => '42', 'kotasampai_id' => '41', 'nominalsupir' => '0.00', 'jarak' => '0.00', 'zona_id' => '0', 'statusaktif' => '2', 'tglmulaiberlaku' => '2023/1/1', 'modifiedby' => 'Ryan',]);        
    }
}
